//! Ex ranges: `:[range]cmd`, `:g`/`:v` and `:normal`.
//!
//! Every expectation below was generated by driving real Neovim through a pty
//! (`nvim -u NONE -i NONE -n --noplugin`, keys typed interactively), the same
//! way `vim_compat` is built — these are the same kind of assertion, kept in
//! their own suite because the address parser is a subsystem of its own.
//!
//! One deliberate divergence, marked at its case: nvim prompts "Backwards
//! range given, OK to swap?" and zedit just swaps. The *result* is identical,
//! which is what is pinned.

const std = @import("std");
const h = @import("../harness.zig");

const ESC = "\x1b";
const CR = "\r";
const target = "/tmp/zedit_it_ex.txt";

const six = "alpha\nbravo\nfoo one\ncharlie\nfoo two\ndelta\n";
const abc = "a\nb\nc\n";

pub fn run(ctx: *h.Ctx) !void {
    // --- :g and :v --------------------------------------------------------
    h.case(ctx, target, "nvim#g1 :g/pat/d keeps the rest", &.{ ":g/foo/d", CR, ":wq", CR }, six, "alpha\nbravo\ncharlie\ndelta\n");
    h.case(ctx, target, "nvim#g2 :v/pat/d is the inverse", &.{ ":v/foo/d", CR, ":wq", CR }, six, "foo one\nfoo two\n");
    h.case(ctx, target, "nvim#g3 :g with :normal", &.{ ":g/foo/normal A;", CR, ":wq", CR }, six, "alpha\nbravo\nfoo one;\ncharlie\nfoo two;\ndelta\n");
    h.case(ctx, target, "nvim#g4 :g takes its own range", &.{ ":2,4g/o/d", CR, ":wq", CR }, six, "alpha\ncharlie\nfoo two\ndelta\n");
    h.case(ctx, target, "nvim#g5 :g with :s on each line", &.{ ":g/foo/s/o/0/g", CR, ":wq", CR }, six, "alpha\nbravo\nf00 0ne\ncharlie\nf00 tw0\ndelta\n");
    h.case(ctx, target, "nvim#g6 :g with no match changes nothing", &.{ ":g/nomatch/d", CR, ":wq", CR }, six, six);
    // Every line matches `^`, so this is the shape that catches an iteration
    // that loses its place as lines are added or removed.
    h.case(ctx, target, "nvim#g7 :g/^/ touches every line", &.{ ":g/^/normal A.", CR, ":wq", CR }, abc, "a.\nb.\nc.\n");
    h.case(ctx, target, "nvim#g8 :g whose command inserts lines", &.{ ":g/a/normal ohi", CR, ":wq", CR }, "a\nb\na\n", "a\nhi\nb\na\nhi\n");

    // --- {range}cmd -------------------------------------------------------
    h.case(ctx, target, "nvim#r1 :2,4d", &.{ ":2,4d", CR, ":wq", CR }, six, "alpha\nfoo two\ndelta\n");
    h.case(ctx, target, "nvim#r2 :%d empties the file", &.{ ":%d", CR, ":wq", CR }, six, "");
    h.case(ctx, target, "nvim#r3 :.,+2d counts from the cursor", &.{ ":.,+2d", CR, ":wq", CR }, six, "charlie\nfoo two\ndelta\n");
    h.case(ctx, target, "nvim#r4 :$-1,$d takes the last two", &.{ ":$-1,$d", CR, ":wq", CR }, six, "alpha\nbravo\nfoo one\ncharlie\n");
    h.case(ctx, target, "nvim#r5 :1,3j joins the range", &.{ ":1,3j", CR, ":wq", CR }, six, "alpha bravo foo one\ncharlie\nfoo two\ndelta\n");
    // nvim indents with a tab here ('noexpandtab' is its default); zedit
    // takes its unit from the surrounding code and falls back to `tab_width`
    // spaces when, as here, nothing in the file is tab-indented. That rule
    // predates ex ranges and is the one `=` already follows — the *range* is
    // what this case pins.
    h.case(ctx, target, "nvim#r6 :2,3> indents the range", &.{ ":2,3>", CR, ":wq", CR }, six, "alpha\n    bravo\n    foo one\ncharlie\nfoo two\ndelta\n");
    h.case(ctx, target, "nvim#r7 pattern addresses on both ends", &.{ ":/foo/,/delta/d", CR, ":wq", CR }, six, "alpha\nbravo\n");
    // nvim asks before running a backwards range; zedit swaps silently. The
    // answer is the same either way, and that is what is asserted.
    h.case(ctx, target, "nvim#r8 a backwards range is swapped", &.{ ":3,1d", CR, ":wq", CR }, six, "charlie\nfoo two\ndelta\n");
    h.case(ctx, target, "nvim#r9 :2,4y fills the register", &.{ ":2,4y", CR, "ggP", ":wq", CR }, six, "bravo\nfoo one\ncharlie\nalpha\nbravo\nfoo one\ncharlie\nfoo two\ndelta\n");

    // --- :normal ----------------------------------------------------------
    h.case(ctx, target, "nvim#n1 :%normal runs on every line", &.{ ":%normal A!", CR, ":wq", CR }, abc, "a!\nb!\nc!\n");
    h.case(ctx, target, "nvim#n2 :normal with no range runs once", &.{ ":normal A!", CR, ":wq", CR }, abc, "a!\nb\nc\n");
    h.case(ctx, target, "nvim#n3 :2,3normal over a range", &.{ ":2,3normal Ix", CR, ":wq", CR }, abc, "a\nxb\nxc\n");
    // `dd` on every line has to keep finding the next one as they vanish.
    h.case(ctx, target, "nvim#n4 :%normal dd empties the file", &.{ ":%normal dd", CR, ":wq", CR }, abc, "");
    h.case(ctx, target, "nvim#n5 :normal! is accepted too", &.{ ":%normal! A?", CR, ":wq", CR }, "a\nb\n", "a?\nb?\n");

    // --- marks, the visual pair, and `;` ----------------------------------
    h.case(ctx, target, "nvim#m1 :'a,'bd between two marks", &.{ "ma", "jj", "mb", ":'a,'bd", CR, ":wq", CR }, six, "charlie\nfoo two\ndelta\n");
    h.case(ctx, target, "nvim#m2 :'<,'>d takes the last selection", &.{ "Vj", ESC, ":'<,'>d", CR, ":wq", CR }, six, "foo one\ncharlie\nfoo two\ndelta\n");
    // `;` moves the cursor to the first address before reading the second,
    // so the `+2` counts from line 2 rather than from line 1.
    h.case(ctx, target, "nvim#m3 :.;+2d counts from the first address", &.{ "j", ":.;+2d", CR, ":wq", CR }, six, "alpha\nfoo two\ndelta\n");

    // --- a bare range just moves ------------------------------------------
    h.case(ctx, target, "nvim#b1 :4 goes to line 4", &.{ ":4", CR, "x", ":wq", CR }, six, "alpha\nbravo\nfoo one\nharlie\nfoo two\ndelta\n");
    h.case(ctx, target, "nvim#b2 :$ goes to the last line", &.{ ":$", CR, "x", ":wq", CR }, six, "alpha\nbravo\nfoo one\ncharlie\nfoo two\nelta\n");
    h.case(ctx, target, "nvim#b3 :1,3 lands on the range's end", &.{ ":1,3", CR, "x", ":wq", CR }, six, "alpha\nbravo\noo one\ncharlie\nfoo two\ndelta\n");
    h.case(ctx, target, "nvim#b4 :+2 is relative to the cursor", &.{ ":+2", CR, "x", ":wq", CR }, six, "alpha\nbravo\noo one\ncharlie\nfoo two\ndelta\n");

    // --- the range parser must not eat ordinary commands ------------------
    // `:g`/`:v` are matched by their delimiter, so the commands that merely
    // start with those letters still work.
    {
        const dir = try ctx.tempDir();
        var s = try h.Session.spawn(ctx.gpa, .{ .argv = &.{ ctx.zedit, "--lsp", "" }, .cwd = dir });
        defer s.finish();
        s.drain(600);
        s.send(ESC); // dismiss the startup screen
        s.drain(200);
        s.send(":vsplit" ++ CR);
        s.drain(500);
        ctx.check(":vsplit is not read as :v", !s.containsPlain(ctx.gpa, "usage: :g/pattern/command"));
        s.send(":only" ++ CR);
        s.drain(300);
        s.send(":g" ++ CR); // a bare :g has no delimiter and no pattern
        s.drain(300);
        ctx.check("a bare :g is refused, not run", s.containsPlain(ctx.gpa, "unknown command") or
            s.containsPlain(ctx.gpa, "usage"));
        s.send(":q!" ++ CR);
        s.drain(200);
    }
}
