//! Tree-sitter autoindent: `o`, `O`, Enter and `cc` take the indent from the
//! grammar's `indents.scm`, not just from the previous line's whitespace.
//!
//! The `#c*` and `#p*` expectations were generated by driving real Neovim
//! (NVIM v0.12.4) through a pty with nvim-treesitter's indent module — the same
//! keys, the same shiftwidth, `indentexpr` set to
//! `v:lua.require'nvim-treesitter'.indentexpr()` — so those cases are ground
//! truth, not memory. The Zig/Go/Rust/JS/TS cases are zedit's own documented
//! expectations: this machine has no nvim parsers for those languages, so
//! there was nothing to ask. They follow the same one-rule model as the
//! verified ones.
//!
//! The `#f*` and `#b*` cases are pinned against plain nvim instead
//! (`-u NONE -i NONE`, `set autoindent`, no filetype), because they are about
//! the *fallback*: a file with no grammar, and a blank reference line. #b1-#b3
//! agree with nvim-treesitter too; #b4 does not — `o` on a blank line is
//! column 0 in plain vim and one block level under nvim-treesitter, and zedit
//! follows vim there (it is the copy rule that applies, the tree having
//! nothing to say about a blank line). Recorded in CLAUDE.md's gap list.
//!
//! Two documented differences from nvim-treesitter, both because zedit
//! evaluates only `@indent.begin` (see CLAUDE.md):
//!   - after a Python `return`, nvim dedents (`@indent.end`) and zedit keeps
//!     the block's indent, which is what vim's plain 'autoindent' does;
//!   - `.txt` and other grammar-less files keep the copy rule outright.

const std = @import("std");
const h = @import("../harness.zig");

const ESC = "\x1b";
const CR = "\r";

pub fn run(ctx: *h.Ctx) !void {
    const c_file = "/tmp/zedit_it_indent.c";
    const py = "/tmp/zedit_it_indent.py";
    const zig = "/tmp/zedit_it_indent.zig";
    const go = "/tmp/zedit_it_indent.go";
    const rs = "/tmp/zedit_it_indent.rs";
    const ts = "/tmp/zedit_it_indent.ts";
    const txt = "/tmp/zedit_it_indent.txt";

    // --- C, nvim+nvim-treesitter verified ------------------------------
    const cfn = "void f(void) {\n}\n";
    h.case(ctx, c_file, "ts-indent#c1 o after an opening brace indents", &.{ "obar", ESC, ":wq", CR }, cfn, "void f(void) {\n    bar\n}\n");
    h.case(ctx, c_file, "ts-indent#c2 Enter at the end of the opener indents", &.{ "A", CR, "bar", ESC, ":wq", CR }, cfn, "void f(void) {\n    bar\n}\n");
    const cbody = "void f(void) {\n    int a;\n}\n";
    h.case(ctx, c_file, "ts-indent#c3 o inside a block keeps the block indent", &.{ "jobar", ESC, ":wq", CR }, cbody, "void f(void) {\n    int a;\n    bar\n}\n");
    h.case(ctx, c_file, "ts-indent#c4 O above the closing brace stays inside", &.{ "GObar", ESC, ":wq", CR }, cbody, "void f(void) {\n    int a;\n    bar\n}\n");
    h.case(ctx, c_file, "ts-indent#c5 cc on a body line keeps its level", &.{ "jccbar", ESC, ":wq", CR }, cbody, "void f(void) {\n    bar\n}\n");
    h.case(ctx, c_file, "ts-indent#c6 O on the first line has nothing to follow", &.{ "Obar", ESC, ":wq", CR }, cfn, "bar\nvoid f(void) {\n}\n");
    // A block that opens and closes on one line opens nothing.
    h.case(ctx, c_file, "ts-indent#c7 a one-line block does not indent", &.{ "obar", ESC, ":wq", CR }, "void f(void) { int a; }\n", "void f(void) { int a; }\nbar\n");
    h.case(ctx, c_file, "ts-indent#c8 struct body indents", &.{ "obar", ESC, ":wq", CR }, "struct S {\n};\n", "struct S {\n    bar\n};\n");
    h.case(
        ctx,
        c_file,
        "ts-indent#c9 case label indents its body",
        &.{ "3G", "obar", ESC, ":wq", CR },
        "void f(void) {\n    switch (x) {\n    case 1:\n    }\n}\n",
        "void f(void) {\n    switch (x) {\n    case 1:\n        bar\n    }\n}\n",
    );
    // Nesting stacks: an `if` brace inside a function brace is two levels.
    h.case(
        ctx,
        c_file,
        "ts-indent#c10 nested braces stack",
        &.{ "2G", "obar", ESC, ":wq", CR },
        "void f(void) {\n    if (x) {\n    }\n}\n",
        "void f(void) {\n    if (x) {\n        bar\n    }\n}\n",
    );

    // Enter counts only the text *before* the cursor: a `{` the split pushes
    // onto the new line has not opened anything on the old one.
    h.case(ctx, c_file, "ts-indent#c11 Enter before the brace does not indent", &.{ "f{", "i", CR, "bar", ESC, ":wq", CR }, cfn, "void f(void) \nbar{\n}\n");

    // --- Python, nvim+nvim-treesitter verified -------------------------
    // No closing token: the opener still ends on its own row while the body is
    // being typed, which is what `#set! indent.immediate` is for.
    h.case(ctx, py, "ts-indent#p1 o after `def f():` indents", &.{ "obar", ESC, ":wq", CR }, "def f():\n", "def f():\n    bar\n");
    h.case(ctx, py, "ts-indent#p2 Enter after `def f():` indents", &.{ "A", CR, "bar", ESC, ":wq", CR }, "def f():\n", "def f():\n    bar\n");
    h.case(ctx, py, "ts-indent#p3 nested if stacks", &.{ "2G", "obar", ESC, ":wq", CR }, "def f():\n    if x:\n        pass\n", "def f():\n    if x:\n        bar\n        pass\n");
    h.case(ctx, py, "ts-indent#p4 O above the body follows the def", &.{ "2G", "Obar", ESC, ":wq", CR }, "def f():\n    pass\n", "def f():\n    bar\n    pass\n");
    h.case(ctx, py, "ts-indent#p5 cc on the body follows the def", &.{ "2G", "ccbar", ESC, ":wq", CR }, "def f():\n    pass\n", "def f():\n    bar\n");
    h.case(ctx, py, "ts-indent#p6 else: opens a block", &.{ "3G", "obar", ESC, ":wq", CR }, "if a:\n    pass\nelse:\n    pass\n", "if a:\n    pass\nelse:\n    bar\n    pass\n");
    // A plain statement opens nothing.
    h.case(ctx, py, "ts-indent#p7 a plain statement does not indent", &.{ "obar", ESC, ":wq", CR }, "x = 1\n", "x = 1\nbar\n");
    // The colon is the last byte of the opener, so a split before it leaves a
    // `def f()` that opens nothing yet — the python twin of #c11.
    h.case(ctx, py, "ts-indent#p8 Enter before the colon does not indent", &.{ "f:", "i", CR, "bar", ESC, ":wq", CR }, "def f():\n", "def f()\nbar:\n");

    // --- zedit's own expectations (no upstream parser to ask) ----------
    h.case(ctx, zig, "ts-indent#z1 zig fn body", &.{ "obar", ESC, ":wq", CR }, "pub fn f() void {\n}\n", "pub fn f() void {\n    bar\n}\n");
    h.case(ctx, zig, "ts-indent#z2 zig struct body", &.{ "obar", ESC, ":wq", CR }, "const S = struct {\n};\n", "const S = struct {\n    bar\n};\n");
    h.case(ctx, rs, "ts-indent#r1 rust fn body", &.{ "obar", ESC, ":wq", CR }, "fn f() {\n}\n", "fn f() {\n    bar\n}\n");
    h.case(ctx, ts, "ts-indent#t1 typescript interface body", &.{ "obar", ESC, ":wq", CR }, "interface X {\n}\n", "interface X {\n    bar\n}\n");
    // Go is tab-indented: the unit follows the file, not the config's spaces.
    h.case(ctx, go, "ts-indent#g1 go block indents with the file's tabs", &.{ "obar", ESC, ":wq", CR }, "func f() {\n\ta := 1\n}\n", "func f() {\n\tbar\n\ta := 1\n}\n");

    // --- the fallback stays vim's 'autoindent' -------------------------
    // No grammar for .txt: `o` copies the previous line's whitespace, and a
    // trailing brace means nothing.
    h.case(ctx, txt, "ts-indent#f1 no grammar keeps the copy rule", &.{ "obar", ESC, ":wq", CR }, "    foo {\n", "    foo {\n    bar\n");
    h.case(ctx, txt, "ts-indent#f2 no grammar, no indent", &.{ "obar", ESC, ":wq", CR }, "foo {\n", "foo {\nbar\n");
    // `O` and `cc` fall back to *their own* line, which is vim's rule and not
    // the same line the syntax model would read (nvim#a2/#a7 pin the
    // one-line case; these are the two-line ones the model could have broken).
    h.case(ctx, txt, "ts-indent#f3 O copies its own line without a grammar", &.{ "2G", "Obar", ESC, ":wq", CR }, "top\n    foo\n", "top\n    bar\n    foo\n");
    h.case(ctx, txt, "ts-indent#f4 cc keeps its own line's indent without a grammar", &.{ "2G", "ccbar", ESC, ":wq", CR }, "top\n    foo\n", "top\n    bar\n");

    // --- a blank line to follow, nvim-verified -------------------------
    // The line above is the one the syntax model reads, and half of real code
    // puts a blank one there. It carries no indent and opens no block, so
    // following it would land `O`/`cc` at column 0 — losing the block's indent.
    // Real nvim (`-u NONE`, `set autoindent`) copies the cursor's own line
    // instead, and so does zedit.
    const cblank = "void f(void) {\n    int a;\n\n    int b;\n}\n";
    h.case(ctx, c_file, "ts-indent#b1 O above a blank line keeps the block indent", &.{ "4G", "Obar", ESC, ":wq", CR }, cblank, "void f(void) {\n    int a;\n\n    bar\n    int b;\n}\n");
    h.case(ctx, c_file, "ts-indent#b2 cc under a blank line keeps the block indent", &.{ "4G", "ccbar", ESC, ":wq", CR }, cblank, "void f(void) {\n    int a;\n\n    bar\n}\n");
    h.case(ctx, py, "ts-indent#b3 python O above a blank line keeps it too", &.{ "4G", "Obar", ESC, ":wq", CR }, "def f():\n    a = 1\n\n    b = 2\n", "def f():\n    a = 1\n\n    bar\n    b = 2\n");
    // …and the rule does not over-reach: `o` *on* the blank line follows the
    // blank line, which is column 0 in plain vim. (nvim-treesitter indents to
    // the block here; zedit keeps vim's answer — see the header.)
    h.case(ctx, c_file, "ts-indent#b4 o on the blank line itself stays at column 0", &.{ "3G", "obar", ESC, ":wq", CR }, cblank, "void f(void) {\n    int a;\n\nbar\n    int b;\n}\n");

    // --- batched input indents like unbatched input --------------------
    // A `.` repeat, a macro replay and plain fast typing all reach the
    // interpreter with no frame in between, so the syntax tree is a revision
    // behind when the indent is decided. Each case below is deliberately *one*
    // chunk: split across chunks (as every case above is) the harness gives
    // the editor a frame and they pass either way.
    const two = "void f(void) {\n}\nvoid g(void) {\n}\n";
    const twice = "void f(void) {\n    bar\n}\nvoid g(void) {\n    bar\n}\n";
    h.case(ctx, c_file, "ts-indent#x1 `.` repeats the indent it made", &.{"obar" ++ ESC ++ "4G." ++ ESC ++ ":wq" ++ CR}, two, twice);
    h.case(ctx, c_file, "ts-indent#x2 a macro replays the indent it recorded", &.{"qqobar" ++ ESC ++ "q4G@q" ++ ESC ++ ":wq" ++ CR}, two, twice);
    h.case(ctx, c_file, "ts-indent#x3 two opens in one batch both indent", &.{"obar" ++ ESC ++ "4Gobaz" ++ ESC ++ ":wq" ++ CR}, two, "void f(void) {\n    bar\n}\nvoid g(void) {\n    baz\n}\n");
    h.case(ctx, py, "ts-indent#x4 python `.` repeats the indent it made", &.{"obar" ++ ESC ++ "4G." ++ ESC ++ ":wq" ++ CR}, "def f():\n    pass\nif x:\n    pass\n", "def f():\n    bar\n    pass\nif x:\n    bar\n    pass\n");
    // --- the `=` operator: give lines the indent they should have, rather
    //     than shifting what is there. Pinned against nvim's cindent, which
    //     agrees byte for byte once the file already uses tabs (nvim --clean
    //     is noexpandtab, and zedit takes its unit from the surrounding code).
    h.case(ctx, c_file, "c-eq1 =G indents a function body", &.{ "=G", ":wq", CR }, "int f(void){\n\t\t\tint x;\n\treturn x;\n}\n", "int f(void){\n\tint x;\n\treturn x;\n}\n");
    h.case(ctx, c_file, "c-eq2 == does one line", &.{ "j", "==", ":wq", CR }, "int f(void){\n\t\t\tint x;\n}\n", "int f(void){\n\tint x;\n}\n");
    h.case(ctx, c_file, "c-eq3 =j does two", &.{ "j", "=j", ":wq", CR }, "int f(void){\nint x;\n\t\t\tint y;\n}\n", "int f(void){\n\tint x;\n\tint y;\n}\n");
    h.case(ctx, c_file, "c-eq4 a nested block stacks", &.{ "=G", ":wq", CR }, "int f(void){\n\tif (x) {\nint y;\n}\n}\n", "int f(void){\n\tif (x) {\n\t\tint y;\n\t}\n}\n");
    h.case(ctx, c_file, "c-eq5 a closer comes back out", &.{ "=G", ":wq", CR }, "int f(void){\n\tint x;\n\t\t\t}\n", "int f(void){\n\tint x;\n}\n");
    h.case(ctx, c_file, "c-eq6 correct indent is left alone", &.{ "=G", ":wq", CR }, "int f(void){\n\tint x;\n}\n", "int f(void){\n\tint x;\n}\n");
    h.case(ctx, c_file, "c-eq7 a blank line stays blank", &.{ "=G", ":wq", CR }, "int f(void){\n\n\t\t\tint x;\n}\n", "int f(void){\n\n\tint x;\n}\n");
    h.case(ctx, c_file, "c-eq8 visual = works too", &.{ "jVj", "=", ":wq", CR }, "int f(void){\n\t\t\tint x;\n}\n", "int f(void){\n\tint x;\n}\n");

}
