//! Viewport positioning: `zz`, `zt` and `zb` put the cursor's line at the
//! centre, the top or the bottom of the window without moving the cursor.
//!
//! The expected line numbers were generated by driving real Neovim through a
//! pty (`nvim -u NONE -i NONE -n --noplugin` in a 24-row terminal, keys typed
//! interactively and `line('w0')`/`line('w$')` written out afterwards), which
//! gives 22 text rows there — a statusline and a command line — and 22 here
//! too, since zedit spends its other two rows on the title bar and its own
//! statusline. On a 100-line file with the cursor on line 50 nvim answers:
//!
//!     zt -> w0=50 w$=71     zz -> w0=40 w$=61     zb -> w0=29 w$=50
//!
//! so `zt` tops at the cursor, `zz` keeps (rows-1)/2 = 10 lines above it and
//! `zb` keeps rows-1 = 21. Both clamp at the start of the buffer; neither
//! clamps at the end, which is why `zt` near EOF leaves a screen of `~`.

const std = @import("std");
const h = @import("../harness.zig");

const ROWS = 24;
const COLS = 80;

/// Open the 100-line file, run `keys`, and assert exactly which lines the
/// window ended up showing — the first and last that must be there, and the
/// two just outside that must not.
fn viewCase(
    ctx: *h.Ctx,
    dir: []const u8,
    name: []const u8,
    keys: []const u8,
    first: []const u8,
    last: []const u8,
    before: ?[]const u8,
    after: ?[]const u8,
) !void {
    var s = try h.Session.spawn(ctx.gpa, .{ .argv = &.{ ctx.zedit, "lines.txt", "--lsp", "" }, .cwd = dir });
    defer s.finish();
    s.drain(600);
    s.send(keys);
    s.drain(400);

    var scr = try h.screenOf(ctx, &s, ROWS, COLS);
    defer scr.deinit();

    var buf: [96]u8 = undefined;
    ctx.check(try std.fmt.bufPrint(&buf, "{s}: {s} is the top line", .{ name, first }), scr.has(ctx.gpa, first));
    ctx.check(try std.fmt.bufPrint(&buf, "{s}: {s} is the bottom line", .{ name, last }), scr.has(ctx.gpa, last));
    if (before) |b|
        ctx.check(try std.fmt.bufPrint(&buf, "{s}: {s} is scrolled off above", .{ name, b }), !scr.has(ctx.gpa, b));
    if (after) |a|
        ctx.check(try std.fmt.bufPrint(&buf, "{s}: {s} is past the bottom", .{ name, a }), !scr.has(ctx.gpa, a));

    s.send(":q!\r");
    s.drain(200);
}

pub fn run(ctx: *h.Ctx) !void {
    const dir = try ctx.tempDir();
    const path = try std.fmt.allocPrint(ctx.gpa, "{s}/lines.txt", .{dir});
    defer ctx.gpa.free(path);

    // L001..L100 — zero-padded so a needle can never match a longer number.
    var content: std.ArrayList(u8) = .empty;
    defer content.deinit(ctx.gpa);
    var line: [8]u8 = undefined;
    for (1..101) |i| try content.appendSlice(ctx.gpa, try std.fmt.bufPrint(&line, "L{d:0>3}\n", .{i}));
    h.writeFile(ctx.io, path, content.items);

    // --- the three positions, on nvim's numbers ---------------------------
    try viewCase(ctx, dir, "nvim#zt 50G zt", "50Gzt", "L050", "L071", "L049", "L072");
    try viewCase(ctx, dir, "nvim#zz 50G zz", "50Gzz", "L040", "L061", "L039", "L062");
    try viewCase(ctx, dir, "nvim#zb 50G zb", "50Gzb", "L029", "L050", "L028", "L051");

    // --- clamping at the start of the buffer, but not at the end ----------
    // `3Gzz` and `3Gzb` both answer w0=1 in nvim: there is nothing above line
    // 1 to give back, so the cursor simply sits wherever it lands.
    try viewCase(ctx, dir, "nvim#zz-top 3G zz clamps", "3Gzz", "L001", "L022", null, "L023");
    try viewCase(ctx, dir, "nvim#zb-top 3G zb clamps", "3Gzb", "L001", "L022", null, "L023");
    // ...and `98Gzt` answers w0=98: vim scrolls past the last line rather
    // than pulling the view back, so only three lines and then `~` show.
    try viewCase(ctx, dir, "nvim#zt-eof 98G zt does not clamp", "98Gzt", "L098", "L100", "L097", null);
    try viewCase(ctx, dir, "nvim#zz-eof 100G zz does not clamp", "100Gzz", "L090", "L100", "L089", null);

    // --- the cursor does not move, and the keys compose -------------------
    // `zz` then `zt` must land exactly where a bare `zt` does (nvim: w0=50).
    try viewCase(ctx, dir, "nvim#zzt 50G zz zt", "50Gzzzt", "L050", "L071", "L049", "L072");

    // --- z<CR> / z. / z- : the same three, plus the first non-blank -------
    // nvim, same 22-row window: z<CR> w0=50, z. w0=40, z- w0=29 — identical
    // to zt/zz/zb. What separates them is the column, checked below.
    try viewCase(ctx, dir, "nvim#zcr 50G z<CR>", "50Gz\r", "L050", "L071", "L049", "L072");
    try viewCase(ctx, dir, "nvim#zdot 50G z.", "50Gz.", "L040", "L061", "L039", "L062");
    try viewCase(ctx, dir, "nvim#zdash 50G z-", "50Gz-", "L029", "L050", "L028", "L051");
    // `z+` starts on the line below the window, `z^` on the one above it.
    // From 50G (which centres: w0=40, w$=61) that is 62 and 39.
    try viewCase(ctx, dir, "nvim#zplus 50G z+", "50Gz+", "L062", "L083", "L061", "L084");
    try viewCase(ctx, dir, "nvim#zcaret 50G z^", "50Gz^", "L018", "L039", "L017", "L040");

    // The column: z<CR>/z./z- go to the first non-blank, zt/zz/zb keep it.
    {
        const ind = try std.fmt.allocPrint(ctx.gpa, "{s}/ind.txt", .{dir});
        defer ctx.gpa.free(ind);
        const Case = struct { name: []const u8, keys: []const u8, want: []const u8 };
        for ([_]Case{
            .{ .name = "nvim#zcol1 z<CR> goes to the first non-blank", .keys = "2G$z\rx:wq\r", .want = "a\n    ndented\nc\n" },
            .{ .name = "nvim#zcol2 z. does too", .keys = "2G$z.x:wq\r", .want = "a\n    ndented\nc\n" },
            .{ .name = "nvim#zcol3 z- does too", .keys = "2G$z-x:wq\r", .want = "a\n    ndented\nc\n" },
            .{ .name = "nvim#zcol4 zt keeps the column", .keys = "2G$ztx:wq\r", .want = "a\n    indente\nc\n" },
        }) |c| {
            h.writeFile(ctx.io, ind, "a\n    indented\nc\n");
            var s = try h.Session.spawn(ctx.gpa, .{ .argv = &.{ ctx.zedit, "ind.txt", "--lsp", "" }, .cwd = dir });
            defer s.finish();
            s.drain(500);
            s.send(c.keys);
            s.drain(500);
            const got = h.readFile(ctx.gpa, ctx.io, ind);
            defer ctx.gpa.free(got);
            ctx.check(c.name, std.mem.eql(u8, got, c.want));
        }
    }

    // --- Ctrl-E / Ctrl-Y : scroll one line, cursor only if pushed --------
    // nvim from 50G (centred, w0=40): Ctrl-E -> w0=41, 3Ctrl-E -> 43,
    // Ctrl-Y -> 39. From `zt` (w0=50, cursor on the top row) Ctrl-E pushes
    // the cursor down with it, to line 51.
    try viewCase(ctx, dir, "nvim#ce1 Ctrl-E scrolls one down", "50G\x05", "L041", "L062", "L040", "L063");
    try viewCase(ctx, dir, "nvim#ce2 a count scrolls that many", "50G3\x05", "L043", "L064", "L042", "L065");
    try viewCase(ctx, dir, "nvim#ce3 Ctrl-Y scrolls one up", "50G\x19", "L039", "L060", "L038", "L061");
    try viewCase(ctx, dir, "nvim#ce4 from zt, Ctrl-E takes the cursor", "50Gzt\x05", "L051", "L072", "L050", "L073");
    try viewCase(ctx, dir, "nvim#ce5 from zt, Ctrl-Y does not", "50Gzt\x19", "L049", "L070", "L048", "L071");
    // The cursor follows only when it would leave the screen: from zt,
    // Ctrl-E then `x` edits line 51, not 50.
    {
        var s = try h.Session.spawn(ctx.gpa, .{ .argv = &.{ ctx.zedit, "lines.txt", "--lsp", "" }, .cwd = dir });
        defer s.finish();
        s.drain(600);
        s.send("50Gzt\x05x:wq\r");
        s.drain(600);
        const got = h.readFile(ctx.gpa, ctx.io, path);
        defer ctx.gpa.free(got);
        ctx.check("Ctrl-E pushes the cursor off the top row", std.mem.indexOf(u8, got, "\n051\n") != null);
    }

    // The cursor stays on its line: `zt` then `x` edits line 50, not line 1.
    {
        var s = try h.Session.spawn(ctx.gpa, .{ .argv = &.{ ctx.zedit, "lines.txt", "--lsp", "" }, .cwd = dir });
        defer s.finish();
        s.drain(600);
        s.send("50Gztx:wq\r");
        s.drain(600);
        const got = h.readFile(ctx.gpa, ctx.io, path);
        defer ctx.gpa.free(got);
        ctx.check("zt leaves the cursor on its own line", std.mem.indexOf(u8, got, "\n050\n") != null);
        ctx.check("...and does not touch the top line", std.mem.indexOf(u8, got, "L001\n") != null);
    }

    // --- sticky scroll: the enclosing scopes pinned to the top ------------
    // Not pinned against nvim — this is VS Code's feature, not vim's. What is
    // being checked is the design claim: the pinned rows are an *overlay*, so
    // every number above still means what it meant, and they yield to the
    // cursor rather than covering it.
    //
    // Each screen read waits for the frame it is about (`drainUntil`) rather
    // than a fixed budget: `drain` gives its time back as soon as any output
    // flows, so a plain `drain` here catches a half-written frame — and a row
    // read from one is missing its tail, which reads exactly like a rendering
    // bug. (It cost an hour to find that out.)
    {
        const zdir = try ctx.tempDir();
        const zf = try std.fmt.allocPrint(ctx.gpa, "{s}/sticky.zig", .{zdir});
        defer ctx.gpa.free(zf);
        var src: std.ArrayList(u8) = .empty;
        defer src.deinit(ctx.gpa);
        try src.appendSlice(ctx.gpa, "const Outer = struct {\n    fn helper(a: u32) u32 {\n");
        var buf: [40]u8 = undefined;
        for (1..91) |i| try src.appendSlice(ctx.gpa, try std.fmt.bufPrint(&buf, "        x += {d:0>3};\n", .{i}));
        try src.appendSlice(ctx.gpa, "        return x;\n    }\n};\n");
        h.writeFile(ctx.io, zf, src.items);

        const first_text_row = 2; // row 1 is the title bar
        // `60G` centres the view, so both openers are far off the top.
        {
            var s = try h.Session.spawn(ctx.gpa, .{ .argv = &.{ ctx.zedit, "sticky.zig", "--lsp", "" }, .cwd = zdir });
            defer s.finish();
            s.drain(900); // the grammar parses after the first paint
            s.send("60G");
            s.drainUntil(ctx.gpa, 3000, "fn helper");
            var scr = try h.screenOf(ctx, &s, ROWS, COLS);
            defer scr.deinit();
            const r1 = try scr.rowText(ctx.gpa, first_text_row);
            defer ctx.gpa.free(r1);
            const r2 = try scr.rowText(ctx.gpa, first_text_row + 1);
            defer ctx.gpa.free(r2);
            ctx.check("the outermost scope is pinned to the top row",
                std.mem.indexOf(u8, r1, "const Outer = struct {") != null);
            ctx.check("...with its own line number", std.mem.indexOf(u8, r1, " 1 ") != null);
            ctx.check("the inner scope is pinned under it",
                std.mem.indexOf(u8, r2, "fn helper") != null);
            s.send(":q!\r");
            s.drain(200);
        }

        // The viewport itself is untouched: the last visible line is the same
        // whether the pinned rows are drawn or not. That is the whole reason
        // this is an overlay rather than rows taken off the top.
        var last_on: []u8 = &.{};
        defer ctx.gpa.free(last_on);
        {
            var s = try h.Session.spawn(ctx.gpa, .{ .argv = &.{ ctx.zedit, "sticky.zig", "--lsp", "" }, .cwd = zdir });
            defer s.finish();
            s.drain(900);
            s.send("60G");
            s.drainUntil(ctx.gpa, 3000, "fn helper");
            var scr = try h.screenOf(ctx, &s, ROWS, COLS);
            defer scr.deinit();
            last_on = try scr.rowText(ctx.gpa, ROWS - 2); // the last text row
            s.send(":q!\r");
            s.drain(200);
        }
        {
            const cfg = h.join(ctx, zdir, "off.cfg");
            defer ctx.gpa.free(cfg);
            h.writeFile(ctx.io, cfg, "sticky_scroll = false\n");
            var s = try h.Session.spawn(ctx.gpa, .{
                .argv = &.{ ctx.zedit, "--config", cfg, "sticky.zig", "--lsp", "" },
                .cwd = zdir,
            });
            defer s.finish();
            s.drain(900);
            s.send("60G");
            s.drainUntil(ctx.gpa, 3000, "x += 071");
            var scr = try h.screenOf(ctx, &s, ROWS, COLS);
            defer scr.deinit();
            const last_off = try scr.rowText(ctx.gpa, ROWS - 2);
            defer ctx.gpa.free(last_off);
            ctx.check("the viewport is the same with the pins and without",
                std.mem.eql(u8, std.mem.trimEnd(u8, last_on, " "), std.mem.trimEnd(u8, last_off, " ")));
            const r1 = try scr.rowText(ctx.gpa, first_text_row);
            defer ctx.gpa.free(r1);
            ctx.check("sticky_scroll = false pins nothing",
                std.mem.indexOf(u8, r1, "fn helper") == null);
            s.send(":q!\r");
            s.drain(200);
        }

        // They yield to the cursor: `zt` puts it on the top row, so there is
        // no room to pin anything and the line it is on stays visible.
        {
            var s = try h.Session.spawn(ctx.gpa, .{ .argv = &.{ ctx.zedit, "sticky.zig", "--lsp", "" }, .cwd = zdir });
            defer s.finish();
            s.drain(900);
            s.send("60Gzt");
            s.drainUntil(ctx.gpa, 3000, "x += 079");
            var scr = try h.screenOf(ctx, &s, ROWS, COLS);
            defer scr.deinit();
            const r1 = try scr.rowText(ctx.gpa, first_text_row);
            defer ctx.gpa.free(r1);
            ctx.check("nothing is pinned over the cursor's own row",
                std.mem.indexOf(u8, r1, "fn helper") == null and std.mem.indexOf(u8, r1, "058") != null);
            // One line down there is room for exactly one, and it is the
            // *innermost* — which function you are in the middle of is what
            // scrolling took away.
            s.send("j");
            s.drainUntil(ctx.gpa, 3000, "fn helper");
            var scr2 = try h.screenOf(ctx, &s, ROWS, COLS);
            defer scr2.deinit();
            const r1b = try scr2.rowText(ctx.gpa, first_text_row);
            defer ctx.gpa.free(r1b);
            ctx.check("one row of room pins one scope, the innermost",
                std.mem.indexOf(u8, r1b, "fn helper") != null);
            s.send(":q!\r");
            s.drain(200);
        }

        // A file with no grammar has no scopes to pin. The fixture is rewritten
        // first: the `Ctrl-E` cases above edit it and save, so by now line 50
        // reads "050" rather than "L050".
        {
            h.writeFile(ctx.io, path, content.items);
            var s = try h.Session.spawn(ctx.gpa, .{ .argv = &.{ ctx.zedit, "lines.txt", "--lsp", "" }, .cwd = dir });
            defer s.finish();
            s.drain(700);
            s.send("60G");
            s.drainUntil(ctx.gpa, 3000, "L071");
            var scr = try h.screenOf(ctx, &s, ROWS, COLS);
            defer scr.deinit();
            const r1 = try scr.rowText(ctx.gpa, first_text_row);
            defer ctx.gpa.free(r1);
            ctx.check("no grammar, nothing pinned", std.mem.indexOf(u8, r1, "L050") != null);
            s.send(":q!\r");
            s.drain(200);
        }
    }
}
