//! Viewport positioning: `zz`, `zt` and `zb` put the cursor's line at the
//! centre, the top or the bottom of the window without moving the cursor.
//!
//! The expected line numbers were generated by driving real Neovim through a
//! pty (`nvim -u NONE -i NONE -n --noplugin` in a 24-row terminal, keys typed
//! interactively and `line('w0')`/`line('w$')` written out afterwards), which
//! gives 22 text rows there — a statusline and a command line — and 22 here
//! too, since zedit spends its other two rows on the title bar and its own
//! statusline. On a 100-line file with the cursor on line 50 nvim answers:
//!
//!     zt -> w0=50 w$=71     zz -> w0=40 w$=61     zb -> w0=29 w$=50
//!
//! so `zt` tops at the cursor, `zz` keeps (rows-1)/2 = 10 lines above it and
//! `zb` keeps rows-1 = 21. Both clamp at the start of the buffer; neither
//! clamps at the end, which is why `zt` near EOF leaves a screen of `~`.

const std = @import("std");
const h = @import("../harness.zig");

const ROWS = 24;
const COLS = 80;

/// Open the 100-line file, run `keys`, and assert exactly which lines the
/// window ended up showing — the first and last that must be there, and the
/// two just outside that must not.
fn viewCase(
    ctx: *h.Ctx,
    dir: []const u8,
    name: []const u8,
    keys: []const u8,
    first: []const u8,
    last: []const u8,
    before: ?[]const u8,
    after: ?[]const u8,
) !void {
    var s = try h.Session.spawn(ctx.gpa, .{ .argv = &.{ ctx.zedit, "lines.txt", "--lsp", "" }, .cwd = dir });
    defer s.finish();
    s.drain(600);
    s.send(keys);
    s.drain(400);

    var scr = try h.screenOf(ctx, &s, ROWS, COLS);
    defer scr.deinit();

    var buf: [96]u8 = undefined;
    ctx.check(try std.fmt.bufPrint(&buf, "{s}: {s} is the top line", .{ name, first }), scr.has(ctx.gpa, first));
    ctx.check(try std.fmt.bufPrint(&buf, "{s}: {s} is the bottom line", .{ name, last }), scr.has(ctx.gpa, last));
    if (before) |b|
        ctx.check(try std.fmt.bufPrint(&buf, "{s}: {s} is scrolled off above", .{ name, b }), !scr.has(ctx.gpa, b));
    if (after) |a|
        ctx.check(try std.fmt.bufPrint(&buf, "{s}: {s} is past the bottom", .{ name, a }), !scr.has(ctx.gpa, a));

    s.send(":q!\r");
    s.drain(200);
}

pub fn run(ctx: *h.Ctx) !void {
    const dir = try ctx.tempDir();
    const path = try std.fmt.allocPrint(ctx.gpa, "{s}/lines.txt", .{dir});
    defer ctx.gpa.free(path);

    // L001..L100 — zero-padded so a needle can never match a longer number.
    var content: std.ArrayList(u8) = .empty;
    defer content.deinit(ctx.gpa);
    var line: [8]u8 = undefined;
    for (1..101) |i| try content.appendSlice(ctx.gpa, try std.fmt.bufPrint(&line, "L{d:0>3}\n", .{i}));
    h.writeFile(ctx.io, path, content.items);

    // --- the three positions, on nvim's numbers ---------------------------
    try viewCase(ctx, dir, "nvim#zt 50G zt", "50Gzt", "L050", "L071", "L049", "L072");
    try viewCase(ctx, dir, "nvim#zz 50G zz", "50Gzz", "L040", "L061", "L039", "L062");
    try viewCase(ctx, dir, "nvim#zb 50G zb", "50Gzb", "L029", "L050", "L028", "L051");

    // --- clamping at the start of the buffer, but not at the end ----------
    // `3Gzz` and `3Gzb` both answer w0=1 in nvim: there is nothing above line
    // 1 to give back, so the cursor simply sits wherever it lands.
    try viewCase(ctx, dir, "nvim#zz-top 3G zz clamps", "3Gzz", "L001", "L022", null, "L023");
    try viewCase(ctx, dir, "nvim#zb-top 3G zb clamps", "3Gzb", "L001", "L022", null, "L023");
    // ...and `98Gzt` answers w0=98: vim scrolls past the last line rather
    // than pulling the view back, so only three lines and then `~` show.
    try viewCase(ctx, dir, "nvim#zt-eof 98G zt does not clamp", "98Gzt", "L098", "L100", "L097", null);
    try viewCase(ctx, dir, "nvim#zz-eof 100G zz does not clamp", "100Gzz", "L090", "L100", "L089", null);

    // --- the cursor does not move, and the keys compose -------------------
    // `zz` then `zt` must land exactly where a bare `zt` does (nvim: w0=50).
    try viewCase(ctx, dir, "nvim#zzt 50G zz zt", "50Gzzzt", "L050", "L071", "L049", "L072");

    // The cursor stays on its line: `zt` then `x` edits line 50, not line 1.
    {
        var s = try h.Session.spawn(ctx.gpa, .{ .argv = &.{ ctx.zedit, "lines.txt", "--lsp", "" }, .cwd = dir });
        defer s.finish();
        s.drain(600);
        s.send("50Gztx:wq\r");
        s.drain(600);
        const got = h.readFile(ctx.gpa, ctx.io, path);
        defer ctx.gpa.free(got);
        ctx.check("zt leaves the cursor on its own line", std.mem.indexOf(u8, got, "\n050\n") != null);
        ctx.check("...and does not touch the top line", std.mem.indexOf(u8, got, "L001\n") != null);
    }
}
