//! Vim-compatibility suite: each case's expected result was generated by
//! driving real Neovim headlessly (NVIM v0.12.4, `--headless -u NONE -i NONE
//! --noplugin`), so these assert byte-for-byte agreement with vim semantics —
//! including the classic traps: `cw` acts like `ce`; `dw` eats trailing
//! spaces but never crosses a newline; `di(`/`ci'` seek forward on the line
//! when the cursor is before the pair; deleting every line writes a 0-byte
//! file; `daw` + `P` round-trips; `J` leaves the cursor on the joining space.

const std = @import("std");
const h = @import("../harness.zig");

const ESC = "\x1b";
const CR = "\r";
const target = "/tmp/zedit_it_compat.txt";

// SGR mouse reports at a *buffer* position. nvim (driven with `-u NONE -i NONE
// -n --noplugin`, `:set mouse=a` typed interactively) draws neither a tab line
// nor a gutter, so its screen cell for 1-based line `l`, 0-based byte `b` is
// (l, b + 1); zedit's title bar takes screen row 1 and its gutter the first 5
// columns, so the same position is (l + 1, b + 6). The expectations below were
// generated by driving that nvim through a pty and reading back the file it
// saved — every one reproduced across repeated runs.
fn press(comptime l: usize, comptime b: usize) []const u8 {
    return std.fmt.comptimePrint("\x1b[<0;{d};{d}M", .{ b + 6, l + 1 });
}
fn release(comptime l: usize, comptime b: usize) []const u8 {
    return std.fmt.comptimePrint("\x1b[<0;{d};{d}m", .{ b + 6, l + 1 });
}
fn drag(comptime l: usize, comptime b: usize) []const u8 {
    return std.fmt.comptimePrint("\x1b[<32;{d};{d}M", .{ b + 6, l + 1 });
}
fn click(comptime l: usize, comptime b: usize) []const u8 {
    return std.fmt.comptimePrint("\x1b[<0;{d};{d}M\x1b[<0;{d};{d}m", .{ b + 6, l + 1, b + 6, l + 1 });
}
/// `n` clicks at one cell, sent in a single write so they land well inside
/// `mousetime` — vim's multi-click, which is derived from the previous press's
/// time and cell rather than from any timer.
fn multi(comptime n: usize, comptime l: usize, comptime b: usize) []const u8 {
    const one = comptime click(l, b);
    return one ** n;
}
/// The same, with the last press still held down: the drag that follows
/// extends by whole words / lines / the block, depending on `n`.
fn multiHold(comptime n: usize, comptime l: usize, comptime b: usize) []const u8 {
    const head = comptime multi(n - 1, l, b);
    const tail = comptime press(l, b);
    return head ++ tail;
}

pub fn run(ctx: *h.Ctx) !void {
    h.case(ctx, target, "nvim#1 dw deletes word + trailing space", &.{ "dw", ":wq", CR }, "foo bar baz\n", "bar baz\n");
    h.case(ctx, target, "nvim#2 cw acts like ce (space survives)", &.{ "cw", "X", ESC, ":wq", CR }, "foo bar\n", "X bar\n");
    h.case(ctx, target, "nvim#3 dw on last word stops at newline", &.{ "wdw", ":wq", CR }, "foo  bar\n", "foo  \n");
    h.case(ctx, target, "nvim#4 dw from mid-word", &.{ "ldw", ":wq", CR }, "foo bar\n", "fbar\n");
    h.case(ctx, target, "nvim#5 dw sole word + dot repeat", &.{ "dwj.", ":wq", CR }, "foo\nbar\n", "\n\n");
    h.case(ctx, target, "nvim#6 d$ empties the line, keeps it", &.{ "d$", ":wq", CR }, "abc def\n", "\n");
    h.case(ctx, target, "nvim#7 2dw", &.{ "2dw", ":wq", CR }, "one two three\n", "three\n");
    h.case(ctx, target, "nvim#8 x then $p pastes after EOL char", &.{ "x$p", ":wq", CR }, "hello\n", "elloh\n");
    h.case(ctx, target, "nvim#9 di( seeks forward to the pair", &.{ "di(", ":wq", CR }, "a(b c)d\n", "a()d\n");
    h.case(ctx, target, "nvim#10 ci( seeks forward", &.{ "ci(", "Z", ESC, ":wq", CR }, "x (abc) y\n", "x (Z) y\n");
    h.case(ctx, target, "nvim#11 ci' seeks forward", &.{ "ci'", "Q", ESC, ":wq", CR }, "foo 'bar' baz\n", "foo 'Q' baz\n");
    h.case(ctx, target, "nvim#12 yy j p linewise paste below", &.{ "yyjp", ":wq", CR }, "aaa\nbbb\nccc\n", "aaa\nbbb\naaa\nccc\n");
    h.case(ctx, target, "nvim#13 J leaves cursor on joining space", &.{ "Jx", ":wq", CR }, "abc\ndef\n", "abcdef\n");
    h.case(ctx, target, "nvim#14 I inserts at first non-blank", &.{ "I", ">", ESC, ":wq", CR }, "  indented\n", "  >indented\n");
    h.case(ctx, target, "nvim#15 ~ toggles case", &.{ "~", ":wq", CR }, "word\n", "Word\n");
    h.case(ctx, target, "nvim#16 delete-all writes 0 bytes", &.{ "ggVGd", ":wq", CR }, "one\ntwo\nthree\n", "");
    h.case(ctx, target, "nvim#17 * jumps to next occurrence", &.{ "*x", ":wq", CR }, "foo bar foo\n", "foo bar oo\n");
    h.case(ctx, target, "nvim#18 3x clamps at EOL", &.{ "3x", ":wq", CR }, "abc\n", "\n");
    h.case(ctx, target, "nvim#19 df<space>", &.{ "df ", ":wq", CR }, "a b c d\n", "b c d\n");
    h.case(ctx, target, "nvim#20 f( then ci( from the paren", &.{ "f(ci(", "X", ESC, ":wq", CR }, "foo(bar)\n", "foo(X)\n");
    h.case(ctx, target, "nvim#21 daw + P round-trips", &.{ "dawP", ":wq", CR }, "one two\n", "one two\n");
    h.case(ctx, target, "nvim#22 visual U uppercases selection", &.{ "veU", ":wq", CR }, "hello world\n", "HELLO world\n");
    h.case(ctx, target, "nvim#23 dw then dot at new position", &.{ "dw.", ":wq", CR }, "abc def ghi\n", "ghi\n");
    h.case(ctx, target, "nvim#24 ddp swaps lines", &.{ "ddp", ":wq", CR }, "x\ny\nz\n", "y\nx\nz\n");
    h.case(ctx, target, "nvim#25 w then cw on second word", &.{ "wcw", "ZZZ", ESC, ":wq", CR }, "aaa bbb\n", "aaa ZZZ\n");

    // :s substitution — expected results generated by the same headless nvim
    // (patterns chosen to mean the same thing in vim magic and zedit's modern
    // regex syntax).
    h.case(ctx, target, "nvim#s1 :%s g flag replaces all", &.{ ":%s/foo/bar/g\r", ":wq", CR }, "foo foo\nxfoo\n", "bar bar\nxbar\n");
    h.case(ctx, target, "nvim#s2 :s current line, first only", &.{ ":s/o/0/\r", ":wq", CR }, "foo\nfoo\n", "f0o\nfoo\n");
    h.case(ctx, target, "nvim#s3 :2,3s range", &.{ ":2,3s/a/X/g\r", ":wq", CR }, "aa\naa\naa\naa\n", "aa\nXX\nXX\naa\n");
    h.case(ctx, target, "nvim#s4 dot metachar", &.{ ":%s/b.d/X/g\r", ":wq", CR }, "bad bed\nbid\n", "X X\nX\n");
    h.case(ctx, target, "nvim#s5 anchor ^ prefixes lines", &.{ ":%s/^/> /\r", ":wq", CR }, "a\nb\n", "> a\n> b\n");
    h.case(ctx, target, "nvim#s6 i flag ignores case", &.{ ":%s/FOO/x/gi\r", ":wq", CR }, "FOO foo\n", "x x\n");
    h.case(ctx, target, "nvim#s7 character classes", &.{ ":%s/[0-9][0-9]*/N/g\r", ":wq", CR }, "a1 b22 c333\n", "aN bN cN\n");
    h.case(ctx, target, "nvim#s8 no match leaves file unchanged", &.{ ":%s/xyz/Q/g\r", ":wq", CR }, "no match here\n", "no match here\n");

    // Jumplist (Ctrl-o = \x0f back, Ctrl-i = Tab forward) — nvim-verified.
    h.case(ctx, target, "nvim#j1 G then Ctrl-o returns", &.{ "G\x0fx", ":wq", CR }, "aaa\nbbb\nccc\nddd\neee\n", "aa\nbbb\nccc\nddd\neee\n");
    h.case(ctx, target, "nvim#j2 search then Ctrl-o returns to origin", &.{ "/ddd\r\x0fx", ":wq", CR }, "aaa\nbbb\nccc\nddd\neee\n", "aa\nbbb\nccc\nddd\neee\n");
    h.case(ctx, target, "nvim#j3 Ctrl-o then Ctrl-i goes forward again", &.{ "G\x0f\tx", ":wq", CR }, "aaa\nbbb\nccc\nddd\neee\n", "aaa\nbbb\nccc\nddd\nee\n");

    // Autoindent (nvim has 'autoindent' on by default; ours matches).
    h.case(ctx, target, "nvim#a1 o inherits indent", &.{ "obar", ESC, ":wq", CR }, "    foo\n", "    foo\n    bar\n");
    h.case(ctx, target, "nvim#a2 O inherits indent", &.{ "Obar", ESC, ":wq", CR }, "    foo\n", "    bar\n    foo\n");
    h.case(ctx, target, "nvim#a3 Enter inherits indent", &.{ "A\rbar", ESC, ":wq", CR }, "    foo\n", "    foo\n    bar\n");
    h.case(ctx, target, "nvim#a4 blank o-line is stripped on Esc", &.{ "o", ESC, ":wq", CR }, "    foo\n", "    foo\n\n");
    h.case(ctx, target, "nvim#a5 blank intermediate stripped, indent carries", &.{ "A\r\rbar", ESC, ":wq", CR }, "    foo\n", "    foo\n\n    bar\n");
    h.case(ctx, target, "nvim#a6 Enter mid-line moves tail with indent", &.{ "fbi\r", ESC, ":wq", CR }, "    foo bar\n", "    foo \n    bar\n");
    h.case(ctx, target, "nvim#a7 cc keeps the indent", &.{ "ccbar", ESC, ":wq", CR }, "    foo\n", "    bar\n");
    h.case(ctx, target, "nvim#a8 tab indent copied verbatim", &.{ "obar", ESC, ":wq", CR }, "\tfoo\n", "\tfoo\n\tbar\n");
    h.case(ctx, target, "nvim#a9 blank Enter-line stripped on Esc", &.{ "A\r", ESC, ":wq", CR }, "    foo\n", "    foo\n\n");

    // Counted find-char: `[count]f/t/F/T` and `[count];`. Ground truth from
    // headless nvim on "alpha beta gamma alpha beta" — vim counts occurrences
    // and fails the motion outright when there are too few.
    const ff = "alpha beta gamma alpha beta\n";
    h.case(ctx, target, "nvim#f1 3fa lands on the third a", &.{ "3fa", "x", ":wq", CR }, ff, "alpha beta gmma alpha beta\n");
    h.case(ctx, target, "nvim#f2 2ta stops before the second a", &.{ "2ta", "x", ":wq", CR }, ff, "alpha bea gamma alpha beta\n");
    h.case(ctx, target, "nvim#f3 d3fa deletes through the third a", &.{ "d3fa", ":wq", CR }, ff, "mma alpha beta\n");
    h.case(ctx, target, "nvim#f4 2; repeats the find twice", &.{ "fa", "2;", "x", ":wq", CR }, ff, "alpha beta gmma alpha beta\n");
    h.case(ctx, target, "nvim#f5 $3Fa searches backwards by count", &.{ "$", "3Fa", "x", ":wq", CR }, ff, "alpha beta gamm alpha beta\n");
    h.case(ctx, target, "nvim#f6 a count past the last match does nothing", &.{ "9fa", "x", ":wq", CR }, ff, "lpha beta gamma alpha beta\n");

    // The undo tree: `g-`/`g+` walk states in the order they were made, so a
    // change stranded by undo-then-edit is still reachable. Ground truth from
    // headless nvim on "one" with the same keys.
    const ut = "one\n";
    h.case(ctx, target, "nvim#u1 u returns to the state before the insert", &.{ "IA", ESC, "u", ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u2 editing after an undo replaces the redo", &.{ "IA", ESC, "u", "IB", ESC, ":wq", CR }, ut, "Bone\n");
    h.case(ctx, target, "nvim#u3 g- reaches the abandoned branch", &.{ "IA", ESC, "u", "IB", ESC, "g-", ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u4 g- again reaches the original", &.{ "IA", ESC, "u", "IB", ESC, "g-", "g-", ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u5 g+ walks back forward in time", &.{ "IA", ESC, "u", "IB", ESC, "g-", "g-", "g+", ":wq", CR }, ut, "Aone\n");

    // `:earlier` / `:later`, counted in changes and in time. Ground truth from
    // real nvim driven through a pty (running the keys as `-c` arguments joins
    // the two inserts into one undo block and hides the difference).
    h.case(ctx, target, "nvim#u6 :earlier 1 steps back one change", &.{ "IA", ESC, "IB", ESC, ":earlier 1", CR, ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u7 :earlier 2 steps back two", &.{ "IA", ESC, "IB", ESC, ":earlier 2", CR, ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u8 :later 1 comes forward again", &.{ "IA", ESC, "IB", ESC, ":earlier 2", CR, ":later 1", CR, ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u9 :earlier 1h clamps to the oldest state", &.{ "IA", ESC, "IB", ESC, ":earlier 1h", CR, ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u10 :later 1h clamps to the newest", &.{ "IA", ESC, "IB", ESC, ":earlier 1h", CR, ":later 1h", CR, ":wq", CR }, ut, "BAone\n");

    // `:earlier Nf` / `:later Nf` count file writes, not changes. Ground truth
    // from real nvim through a pty: write, edit, write, edit, then walk back.
    const wr = &[_][]const u8{ "IA", ESC, ":w", CR, "IB", ESC, ":w", CR, "IC", ESC };
    h.case(ctx, target, "nvim#u11 :earlier 1f returns to the last write", wr ++ &[_][]const u8{ ":earlier 1f", CR, ":wq", CR }, ut, "BAone\n");
    h.case(ctx, target, "nvim#u12 :earlier 2f goes back two writes", wr ++ &[_][]const u8{ ":earlier 2f", CR, ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u13 :earlier 3f clamps past the first write", wr ++ &[_][]const u8{ ":earlier 3f", CR, ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u14 :later 1f comes forward a write", wr ++ &[_][]const u8{ ":earlier 2f", CR, ":later 1f", CR, ":wq", CR }, ut, "BAone\n");
    h.case(ctx, target, "nvim#u15 :earlier 1f with no writes goes to the start", &.{ "IA", ESC, "IB", ESC, ":earlier 1f", CR, ":wq", CR }, ut, "one\n");

    // Visual-mode "around" objects — nvim-verified on "x = add(a, b)".
    const va = "x = add(a, b)\n";
    h.case(ctx, target, "nvim#v1 va( takes the brackets", &.{ "fa", "va(d", ":wq", CR }, va, "x = add\n");
    h.case(ctx, target, "nvim#v2 vi( keeps them", &.{ "fa", "vi(d", ":wq", CR }, va, "x = add()\n");
    h.case(ctx, target, "nvim#v3 vaw takes the word and its space", &.{ "fa", "vawd", ":wq", CR }, va, "x =(a, b)\n");
    h.case(ctx, target, "nvim#v4 vaW takes the whole WORD", &.{ "fa", "vaWd", ":wq", CR }, va, "x = b)\n");

    // Command-line history (Up = \x1b[A, Down = \x1b[B) — nvim-verified.
    // ':' Up recalls the last ex command; Enter replays it.
    h.case(ctx, target, "nvim#h1 : Up replays last command", &.{ ":s/a/X/\r", "j", ":", "\x1b[A", "\r", ":wq", CR }, "aa\naa\n", "Xa\nXa\n");
    // Up filters by the typed prefix: ':s' skips the ':2' entry.
    h.case(ctx, target, "nvim#h2 Up filters by typed prefix", &.{ ":s/a/X/\r", ":2\r", ":s", "\x1b[A", "\r", ":wq", CR }, "aa\naa\naa\n", "Xa\nXa\naa\n");
    // '/' has its own history; Up recalls the last pattern.
    h.case(ctx, target, "nvim#h3 / Up recalls last search", &.{ "/alpha\r", "gg", "/", "\x1b[A", "\r", "x", ":wq", CR }, "one\nalpha\ntwo\nalpha\n", "one\nlpha\ntwo\nalpha\n");
    // Down past the newest entry restores the typed-but-unrun line.
    h.case(ctx, target, "nvim#h4 Down restores the typed line", &.{ ":s/a/X/\r", "j", ":s/a/Y/", "\x1b[A", "\x1b[B", "\r", ":wq", CR }, "aa\naa\n", "Xa\nYa\n");
    // :qa with unsaved changes refuses (nvim E37); the :wq still writes.
    h.case(ctx, target, "nvim#h5 :qa refuses unsaved changes", &.{ "x", ":qa\r", ":wq", CR }, "aa\n", "a\n");

    // Mid-line command-line editing (Left/Right/Home/End/Ctrl-b/Ctrl-e move a
    // cursor within the line; typing inserts, backspace deletes before it).
    // Every expectation generated by driving real nvim through a tmux pty and
    // reading the file it saved, e.g. e1's probe: `:s/a/XY/` Left Left Left
    // `Z` CR on "ab" left the file "ZXYb" — the Z landed before the X.
    h.case(ctx, target, "nvim#e1 Left then typing inserts before the cursor", &.{ ":s/a/XY/", "\x1b[D\x1b[D\x1b[D", "Z", "\r", ":wq", CR }, "ab\n", "ZXYb\n");
    // Probe: `:s/a/X/` Home `2` -> ":2s/a/X/" (the 2 landed at column 0).
    h.case(ctx, target, "nvim#e2 Home jumps to the start of the line", &.{ ":s/a/X/", "\x1b[H", "2", "\r", ":wq", CR }, "aa\naa\n", "aa\nXa\n");
    // Probe: `:s/aXb/Y/` Left x4 BS -> ":s/ab/Y/" (deleted the char before the cursor).
    h.case(ctx, target, "nvim#e3 backspace deletes before the cursor", &.{ ":s/aXb/Y/", "\x1b[D\x1b[D\x1b[D\x1b[D", "\x7f", "\r", ":wq", CR }, "ab\n", "Y\n");
    // Probe: `:s/a/Q/` Left Left Right `R` -> ":s/a/QR/" (Right moved right mid-line).
    h.case(ctx, target, "nvim#e4 Right moves the cursor right", &.{ ":s/a/Q/", "\x1b[D\x1b[D", "\x1b[C", "R", "\r", ":wq", CR }, "ab\n", "QRb\n");
    // Probe: `:s/a/W` Left Left End `/` -> ":s/a/W/" (End jumped to end-of-line).
    h.case(ctx, target, "nvim#e5 End jumps to the end of the line", &.{ ":s/a/W", "\x1b[D\x1b[D", "\x1b[F", "/", "\r", ":wq", CR }, "ab\n", "Wb\n");
    // Probes: Ctrl-b / Ctrl-e are vim's c_CTRL-B / c_CTRL-E (start / end).
    h.case(ctx, target, "nvim#e6 Ctrl-b to the beginning", &.{ ":s/a/X/", "\x02", "2", "\r", ":wq", CR }, "aa\naa\n", "aa\nXa\n");
    h.case(ctx, target, "nvim#e7 Ctrl-e to the end", &.{ ":s/a/W", "\x1b[D\x1b[D", "\x05", "/", "\r", ":wq", CR }, "ab\n", "Wb\n");
    // Probe: Home BS `2` -> ":2s/a/X/" — backspace at column 0 of a NON-empty
    // line is a no-op in nvim (it neither deletes nor cancels the cmdline).
    h.case(ctx, target, "nvim#e8 backspace at column 0 is a no-op", &.{ ":s/a/X/", "\x1b[H", "\x7f", "2", "\r", ":wq", CR }, "aa\naa\n", "aa\nXa\n");
    // Probe: `:` Up recalls ":s/a/X/" with the cursor at END of line, so the
    // typed `g` appends -> ":s/a/X/g" replaced both a's on line 2.
    h.case(ctx, target, "nvim#e9 history recall puts the cursor at the end", &.{ ":s/a/X/\r", "j", ":", "\x1b[A", "g", "\r", ":wq", CR }, "aa\naa\n", "Xa\nXX\n");
    // Probe: `:s/a/XY/` Left x3 CR -> "XYb", not "Xb" — Enter runs the WHOLE
    // line, never just the part before the cursor.
    h.case(ctx, target, "nvim#e10 Enter mid-line runs the whole line", &.{ ":s/a/XY/", "\x1b[D\x1b[D\x1b[D", "\r", ":wq", CR }, "ab\n", "XYb\n");

    // Paragraph motions and text objects ({ } ip ap) — nvim-verified.
    const P2 = "aaa\nbbb\n\nccc\nddd\n";
    const P3 = "aaa\n\nbbb\n\nccc\n";
    h.case(ctx, target, "nvim#p1 } lands on the empty line", &.{ "}x", ":wq", CR }, P2, P2);
    h.case(ctx, target, "nvim#p2 d} from col 0 is linewise", &.{ "d}", ":wq", CR }, P2, "\nccc\nddd\n");
    h.case(ctx, target, "nvim#p3 d} mid-line stays charwise", &.{ "lld}", ":wq", CR }, P2, "aa\n\nccc\nddd\n");
    h.case(ctx, target, "nvim#p4 { lands on the empty line", &.{ "G{x", ":wq", CR }, P2, P2);
    h.case(ctx, target, "nvim#p5 d{ deletes back to boundary", &.{ "G$d{", ":wq", CR }, P2, "aaa\nbbb\nd\n");
    h.case(ctx, target, "nvim#p6 dip deletes the paragraph", &.{ "dip", ":wq", CR }, P2, "\nccc\nddd\n");
    h.case(ctx, target, "nvim#p7 dap takes the trailing blank", &.{ "dap", ":wq", CR }, P2, "ccc\nddd\n");
    h.case(ctx, target, "nvim#p8 dip on a blank line", &.{ "jdip", ":wq", CR }, "aaa\n\n\nbbb\n", "aaa\nbbb\n");
    h.case(ctx, target, "nvim#p9 dap on last para takes leading blank", &.{ "Gdap", ":wq", CR }, P2, "aaa\nbbb\n");
    h.case(ctx, target, "nvim#p10 vip d is linewise", &.{ "vipd", ":wq", CR }, P2, "\nccc\nddd\n");
    h.case(ctx, target, "nvim#p11 yap P round-trips", &.{ "yapP", ":wq", CR }, P3, "aaa\n\naaa\n\nbbb\n\nccc\n");
    h.case(ctx, target, "nvim#p12 2} skips a boundary", &.{ "2}x", ":wq", CR }, P3, P3);
    h.case(ctx, target, "nvim#p13 whitespace-only line is no boundary", &.{ "}x", ":wq", CR }, "aaa\n  \nbbb\n\nccc\n", "aaa\n  \nbbb\n\nccc\n");
    h.case(ctx, target, "nvim#p14 cip changes the paragraph", &.{ "cip", "XX", ESC, ":wq", CR }, P2, "XX\n\nccc\nddd\n");
    h.case(ctx, target, "nvim#p15 } at EOF clamps to last line", &.{ "}}x", ":wq", CR }, P2, "aaa\nbbb\n\nccc\ndd\n");
    h.case(ctx, target, "nvim#p16 d2ap takes two paragraphs", &.{ "d2ap", ":wq", CR }, P3, "ccc\n");

    // The cursor never sits past the last character in normal mode, so
    // commands after `$` act on the last character (regression: `$x` used to
    // do nothing and `$dh`/`$d0`/`$db` were all off by one). nvim-verified.
    h.case(ctx, target, "nvim#c1 $x deletes the last character", &.{ "$x", ":wq", CR }, "abc\n", "ab\n");
    h.case(ctx, target, "nvim#c2 $dh deletes before the last", &.{ "$dh", ":wq", CR }, "abc\n", "ac\n");
    h.case(ctx, target, "nvim#c3 $d0 keeps the last character", &.{ "$d0", ":wq", CR }, "abc\n", "c\n");
    h.case(ctx, target, "nvim#c4 $db from end of line", &.{ "$db", ":wq", CR }, "abc def\n", "abc f\n");
    h.case(ctx, target, "nvim#c5 $dF exclusive backward find", &.{ "$dFc", ":wq", CR }, "abc def\n", "abf\n");

    // Mouse (nvim `mouse=a`): a click moves the cursor, a drag selects. Every
    // expectation below came out of real nvim through a pty — see the helpers
    // at the top of this file for the coordinate mapping.
    const M = "abcdefghij\nklmnopqrst\nuvwxyz1234\n";
    // A pending operator takes the click as an exclusive charwise motion,
    // across lines and in either direction, and ignores any count.
    h.case(ctx, target, "nvim#m1 d + click is exclusive charwise", &.{ "d", click(2, 4), ":wq", CR }, M, "opqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m2 d + click backwards", &.{ "G$", "d", click(2, 2), ":wq", CR }, M, "abcdefghij\nkl4\n");
    // vim's exclusive rules: an end in column 0 becomes linewise when the
    // start was at or before its line's first non-blank, else it stops at the
    // end of the previous line.
    h.case(ctx, target, "nvim#m3 d + click at column 0 is linewise", &.{ "d", click(3, 0), ":wq", CR }, M, "uvwxyz1234\n");
    h.case(ctx, target, "nvim#m4 d mid-line + click at column 0", &.{ "ll", "d", click(3, 0), ":wq", CR }, M, "ab\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m5 y + click yanks linewise", &.{ "y", click(3, 0), "P", ":wq", CR }, M, "abcdefghij\nklmnopqrst\nabcdefghij\nklmnopqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m6 d2 + click ignores the count", &.{ "d2", click(2, 4), ":wq", CR }, M, "opqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m7 a pending count is discarded", &.{ "3", click(2, 4), "x", ":wq", CR }, M, "abcdefghij\nklmnpqrst\nuvwxyz1234\n");
    // A click ends a selection, from `v` and from `V` alike.
    h.case(ctx, target, "nvim#m8 click ends visual", &.{ "v", click(2, 4), "x", ":wq", CR }, M, "abcdefghij\nklmnpqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m9 click ends V-LINE", &.{ "V", click(2, 4), "x", ":wq", CR }, M, "abcdefghij\nklmnpqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m10 insert mode continues at the click", &.{ "i", click(2, 4), "QQQ", ESC, ":wq", CR }, M, "abcdefghij\nklmnQQQopqrst\nuvwxyz1234\n");
    // curswant keeps the *clicked* column, not the clamped one.
    h.case(ctx, target, "nvim#m11 click past EOL keeps the column for k", &.{ click(3, 39), "k", "x", ":wq", CR }, "short\nabcdefghijklmnopqrst\nxy\n", "short\nabcdefghijklmnopqrs\nxy\n");
    // A click below the last line clamps to it and keeps the column (screen
    // row 20 is a `~` row in both editors for this three-line file).
    h.case(ctx, target, "nvim#m12 click past EOF clamps to the last line", &.{ "\x1b[<0;10;20M\x1b[<0;10;20m", "x", ":wq", CR }, M, "abcdefghij\nklmnopqrst\nuvwxz1234\n");
    // Drag: the press anchors, motion extends, the selection is inclusive.
    h.case(ctx, target, "nvim#m13 drag selects from the press", &.{ press(1, 2), drag(2, 5), drag(3, 5), release(3, 5), "d", ":wq", CR }, M, "ab1234\n");
    h.case(ctx, target, "nvim#m14 a drag out of V-LINE is charwise", &.{ "V", press(1, 2), drag(2, 5), release(2, 5), "d", ":wq", CR }, M, "abqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m15 a drag to the same cell stays normal", &.{ press(2, 4), drag(2, 4), release(2, 4), "x", ":wq", CR }, M, "abcdefghij\nklmnpqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m16 the release extends the selection too", &.{ press(1, 2), drag(2, 5), release(3, 1), "d", ":wq", CR }, M, "abwxyz1234\n");
    h.case(ctx, target, "nvim#m17 a click leaves the drag selection", &.{ press(1, 2), drag(2, 5), release(2, 5), click(3, 3), "x", ":wq", CR }, M, "abcdefghij\nklmnopqrst\nuvwyz1234\n");
    // A click pushes no jumplist entry: Ctrl-o returns to `G`'s origin.
    h.case(ctx, target, "nvim#m18 a click adds no jump", &.{ "G", click(2, 4), "\x0f", "x", ":wq", CR }, M, "bcdefghij\nklmnopqrst\nuvwxyz1234\n");
    // A click past both ends reaches end-of-line, so `d` empties the line.
    h.case(ctx, target, "nvim#m19 d + click past EOL empties the line", &.{ "d", "\x1b[<0;40;10M\x1b[<0;40;10m", ":wq", CR }, "one two three\n", "\n");
    // A pending operator is consumed by the *press*; the drag and release that
    // follow it find nothing to extend and change nothing more.
    h.case(ctx, target, "nvim#m20 d + press-drag-release acts at the press", &.{ "d", press(2, 6), drag(3, 7), release(3, 7), ":wq", CR }, M, "qrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m21 y + press-drag-release yanks at the press", &.{ "y", press(2, 6), drag(3, 7), release(3, 7), "P", ":wq", CR }, M, "abcdefghij\nklmnopabcdefghij\nklmnopqrst\nuvwxyz1234\n");
    // `.` repeats an operator+click: vim's redo stores the *screen* position,
    // so the repeat re-resolves the same cell from wherever the cursor now is.
    // (Without the click in the dot capture, `.` silently repeated whatever
    // change came before it — `dl` here — instead.)
    h.case(ctx, target, "nvim#m22 . repeats an operator+click", &.{ "d", click(1, 4), "j0", ".", ":wq", CR }, M, "efgh\nklmnopqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m23 . after an earlier change repeats the click", &.{ "dl", "d", click(2, 4), ".", ":wq", CR }, M, "yz1234\n");
    // An exclusive end in column 0 of line *2* steps back to line 1 — the one
    // row where the step used to underflow and abort the editor.
    h.case(ctx, target, "nvim#m24 d + click at column 0 of line 2", &.{ "d", click(2, 0), ":wq", CR }, M, "klmnopqrst\nuvwxyz1234\n");
    // …and the line it steps back to must be the right one: with lines of
    // different lengths the span used to stop at the *previous* line's width.
    h.case(ctx, target, "nvim#m25 d + click at column 0, unequal lines", &.{ "ll", "d", click(3, 0), ":wq", CR }, "abXY\nklmnopqrst\nuvw\n", "ab\nuvw\n");
    // The same rule with no mouse at all (`}` is exclusive too), which is how
    // the underflow and the wrong-length span were reachable before clicks.
    h.case(ctx, target, "nvim#m26 d} onto a blank line 2", &.{ "d}", ":wq", CR }, "abc\n\ndef\n", "\ndef\n");
    h.case(ctx, target, "nvim#m27 d} stops at its own line's end", &.{ "jl", "d}", ":wq", CR }, "ab\nlonglongline\n\nx\n", "ab\nl\n\nx\n");
    // A click recorded in a macro replays as a click.
    h.case(ctx, target, "nvim#m28 a macro replays a click", &.{ "qa", click(3, 3), "x", "q", "@a", ":wq", CR }, M, "abcdefghij\nklmnopqrst\nuvwz1234\n");

    // Multi-click gestures: 2 = the word, 3 = the line (linewise), 4 = one
    // blockwise cell, and the fifth click starts the cycle again. The word is
    // vim's *mouse* word, which is not `iw`: punctuation goes through `%` when
    // there is an item at or after the click on that line, and otherwise
    // groups only with its own class.
    const W = "hello, world foo\n  indented text here\nfoo.bar(baz) end\n";
    const P = "abc..def(g)\na(b)cd.ef\na->b(c)\nabc<def>ghi\n";
    const G = "alpha beta gamma delta epsilon\nsecond line here now\nthird line here now\n";
    h.case(ctx, target, "nvim#m29 double click selects the word", &.{ multi(2, 1, 8), "d", ":wq", CR }, W, "hello,  foo\n  indented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m30 double click at column 0", &.{ multi(2, 1, 0), "d", ":wq", CR }, W, ", world foo\n  indented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m31 double click past EOL takes the last word", &.{ multi(2, 1, 39), "d", ":wq", CR }, W, "hello, world \n  indented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m32 double click on punctuation is not iw", &.{ multi(2, 1, 5), "d", ":wq", CR }, W, "hello world foo\n  indented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m33 double click takes a whole blank run", &.{ multi(2, 2, 0), "d", ":wq", CR }, W, "hello, world foo\nindented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m34 double click runs % from the click", &.{ multi(2, 1, 3), "d", ":wq", CR }, P, "abc\na(b)cd.ef\na->b(c)\nabc<def>ghi\n");
    h.case(ctx, target, "nvim#m35 % only looks forward", &.{ multi(2, 2, 6), "d", ":wq", CR }, P, "abc..def(g)\na(b)cdef\na->b(c)\nabc<def>ghi\n");
    h.case(ctx, target, "nvim#m36 -> reaches the pair behind it", &.{ multi(2, 3, 1), "d", ":wq", CR }, P, "abc..def(g)\na(b)cd.ef\na\nabc<def>ghi\n");
    h.case(ctx, target, "nvim#m37 <> is not a matchpair", &.{ multi(2, 4, 3), "d", ":wq", CR }, P, "abc..def(g)\na(b)cd.ef\na->b(c)\nabcdef>ghi\n");
    h.case(ctx, target, "nvim#m38 triple click selects the line", &.{ multi(3, 2, 4), "d", ":wq", CR }, M, "abcdefghij\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m39 triple click past EOL is the same line", &.{ multi(3, 2, 39), "d", ":wq", CR }, M, "abcdefghij\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m40 quadruple click selects one cell", &.{ multi(4, 2, 4), "d", ":wq", CR }, M, "abcdefghij\nklmnpqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m41 a fifth click is a plain click", &.{ multi(5, 1, 8), "x", ":wq", CR }, W, "hello, wrld foo\n  indented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m42 a click one cell over does not chain", &.{ comptime click(1, 8) ++ click(1, 9), "x", ":wq", CR }, W, "hello, wold foo\n  indented text here\nfoo.bar(baz) end\n");
    // Dragging after a multi-click extends by whole words / lines / a block,
    // in both directions, with the clicked word always kept whole.
    h.case(ctx, target, "nvim#m43 a drag after a double click extends by words", &.{ multiHold(2, 1, 7), drag(1, 13), release(1, 13), "d", ":wq", CR }, G, "alpha  delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m44 …backwards too", &.{ multiHold(2, 1, 7), drag(1, 2), release(1, 2), "d", ":wq", CR }, G, " gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m45 …snapping to a blank run", &.{ multiHold(2, 1, 7), drag(1, 10), release(1, 10), "d", ":wq", CR }, G, "alpha gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m46 a release at the press keeps the word", &.{ multiHold(2, 1, 7), release(1, 7), "d", ":wq", CR }, G, "alpha  gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m47 a drag after a triple click is linewise", &.{ multiHold(3, 1, 7), drag(2, 5), release(2, 5), "d", ":wq", CR }, G, "third line here now\n");
    h.case(ctx, target, "nvim#m48 a drag after a quadruple click is a block", &.{ multiHold(4, 1, 7), drag(3, 13), release(3, 13), "d", ":wq", CR }, G, "alpha bma delta epsilon\nsecond re now\nthird le now\n");
    // Insert Visual: a gesture begun in insert mode returns to insert —
    // whether it ends with Esc, with an operator, or with a plain click.
    h.case(ctx, target, "nvim#m49 insert + double click, Esc resumes insert", &.{ "i", multi(2, 1, 7), ESC, "QQ", ESC, ":wq", CR }, G, "alpha betQQa gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m50 insert + drag, d resumes insert", &.{ "i", press(1, 2), drag(1, 8), release(1, 8), "d", "QQ", ESC, ":wq", CR }, G, "alQQa gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m51 insert + triple click keeps the clicked column", &.{ "i", multi(3, 1, 7), ESC, "QQ", ESC, ":wq", CR }, G, "alpha bQQeta gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m52 a macro replays a double click", &.{ "qa", multi(2, 1, 7), "x", "q", "@a", ":wq", CR }, G, "alpha   delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m53 a click inside Insert Visual keeps typing", &.{ "i", multi(2, 1, 7), click(2, 3), "QQ", ESC, ":wq", CR }, G, "alpha beta gamma delta epsilon\nsecQQond line here now\nthird line here now\n");
    // Every press decides the click count, wherever it lands — vim works it
    // out in the input layer, before the click is routed anywhere — so a press
    // on chrome breaks a chain in two. The command line is the last screen row
    // in both editors (24), and a press there is inert in both.
    const cmdrow = "\x1b[<0;40;24M\x1b[<0;40;24m";
    h.case(ctx, target, "nvim#m54 a press on the command line breaks the chain", &.{ comptime click(1, 7) ++ cmdrow ++ click(1, 7), "x", ":wq", CR }, G, "alpha bta gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m55 …and does not just delay it", &.{ comptime click(1, 7) ++ click(1, 7) ++ cmdrow ++ click(1, 7), "x", ":wq", CR }, G, "alpha bta gamma delta epsilon\nsecond line here now\nthird line here now\n");

    // Regex `/` search: the pattern jumps, then x edits at the match.
    h.case(ctx, target, "regex / search jumps to match", &.{ "/b.d\r", "x", ":wq", CR }, "xxx\nbad\n", "xxx\nad\n");
    // Capture groups in the replacement swap two words.
    h.case(ctx, target, "capture groups in :s replacement", &.{ ":%s/(\\w+) (\\w+)/\\2 \\1/\r", ":wq", CR }, "one two\n", "two one\n");
}
