//! Vim-compatibility suite: each case's expected result was generated by
//! driving real Neovim headlessly (NVIM v0.12.4, `--headless -u NONE -i NONE
//! --noplugin`), so these assert byte-for-byte agreement with vim semantics —
//! including the classic traps: `cw` acts like `ce`; `dw` eats trailing
//! spaces but never crosses a newline; `di(`/`ci'` seek forward on the line
//! when the cursor is before the pair; deleting every line writes a 0-byte
//! file; `daw` + `P` round-trips; `J` leaves the cursor on the joining space.

const std = @import("std");
const h = @import("../harness.zig");

const ESC = "\x1b";
const CR = "\r";
const CV = "\x16"; // Ctrl-v: blockwise visual
const target = "/tmp/zedit_it_compat.txt";

// SGR mouse reports at a *buffer* position. nvim (driven with `-u NONE -i NONE
// -n --noplugin`, `:set mouse=a` typed interactively) draws neither a tab line
// nor a gutter, so its screen cell for 1-based line `l`, 0-based byte `b` is
// (l, b + 1); zedit's title bar takes screen row 1 and its gutter the first 5
// columns, so the same position is (l + 1, b + 6). The expectations below were
// generated by driving that nvim through a pty and reading back the file it
// saved — every one reproduced across repeated runs.
fn press(comptime l: usize, comptime b: usize) []const u8 {
    return std.fmt.comptimePrint("\x1b[<0;{d};{d}M", .{ b + 6, l + 1 });
}
fn release(comptime l: usize, comptime b: usize) []const u8 {
    return std.fmt.comptimePrint("\x1b[<0;{d};{d}m", .{ b + 6, l + 1 });
}
fn drag(comptime l: usize, comptime b: usize) []const u8 {
    return std.fmt.comptimePrint("\x1b[<32;{d};{d}M", .{ b + 6, l + 1 });
}
fn click(comptime l: usize, comptime b: usize) []const u8 {
    return std.fmt.comptimePrint("\x1b[<0;{d};{d}M\x1b[<0;{d};{d}m", .{ b + 6, l + 1, b + 6, l + 1 });
}
/// `n` clicks at one cell, sent in a single write so they land well inside
/// `mousetime` — vim's multi-click, which is derived from the previous press's
/// time and cell rather than from any timer.
fn multi(comptime n: usize, comptime l: usize, comptime b: usize) []const u8 {
    const one = comptime click(l, b);
    return one ** n;
}
/// The same, with the last press still held down: the drag that follows
/// extends by whole words / lines / the block, depending on `n`.
fn multiHold(comptime n: usize, comptime l: usize, comptime b: usize) []const u8 {
    const head = comptime multi(n - 1, l, b);
    const tail = comptime press(l, b);
    return head ++ tail;
}

pub fn run(ctx: *h.Ctx) !void {
    h.case(ctx, target, "nvim#1 dw deletes word + trailing space", &.{ "dw", ":wq", CR }, "foo bar baz\n", "bar baz\n");
    h.case(ctx, target, "nvim#2 cw acts like ce (space survives)", &.{ "cw", "X", ESC, ":wq", CR }, "foo bar\n", "X bar\n");
    h.case(ctx, target, "nvim#3 dw on last word stops at newline", &.{ "wdw", ":wq", CR }, "foo  bar\n", "foo  \n");
    h.case(ctx, target, "nvim#4 dw from mid-word", &.{ "ldw", ":wq", CR }, "foo bar\n", "fbar\n");
    h.case(ctx, target, "nvim#5 dw sole word + dot repeat", &.{ "dwj.", ":wq", CR }, "foo\nbar\n", "\n\n");
    // A count typed *after* the operator multiplies the one before it, which
    // char motions were dropping: `d3j` took two lines where nvim takes four.
    // All three pinned against `nvim -u NONE -i NONE -n --headless`.
    const eight = "l1\nl2\nl3\nl4\nl5\nl6\nl7\nl8\n";
    h.case(ctx, target, "nvim#cnt1 d3j counts the lines below", &.{ "jd3j", ":wq", CR }, eight, "l1\nl6\nl7\nl8\n");
    h.case(ctx, target, "nvim#cnt2 d2j", &.{ "jd2j", ":wq", CR }, eight, "l1\nl5\nl6\nl7\nl8\n");
    h.case(ctx, target, "nvim#cnt3 2d3j multiplies both counts", &.{ "j2d3j", ":wq", CR }, eight, "l1\n");
    h.case(ctx, target, "nvim#6 d$ empties the line, keeps it", &.{ "d$", ":wq", CR }, "abc def\n", "\n");
    h.case(ctx, target, "nvim#7 2dw", &.{ "2dw", ":wq", CR }, "one two three\n", "three\n");
    h.case(ctx, target, "nvim#8 x then $p pastes after EOL char", &.{ "x$p", ":wq", CR }, "hello\n", "elloh\n");
    h.case(ctx, target, "nvim#9 di( seeks forward to the pair", &.{ "di(", ":wq", CR }, "a(b c)d\n", "a()d\n");
    h.case(ctx, target, "nvim#10 ci( seeks forward", &.{ "ci(", "Z", ESC, ":wq", CR }, "x (abc) y\n", "x (Z) y\n");
    h.case(ctx, target, "nvim#11 ci' seeks forward", &.{ "ci'", "Q", ESC, ":wq", CR }, "foo 'bar' baz\n", "foo 'Q' baz\n");
    h.case(ctx, target, "nvim#12 yy j p linewise paste below", &.{ "yyjp", ":wq", CR }, "aaa\nbbb\nccc\n", "aaa\nbbb\naaa\nccc\n");
    h.case(ctx, target, "nvim#13 J leaves cursor on joining space", &.{ "Jx", ":wq", CR }, "abc\ndef\n", "abcdef\n");
    h.case(ctx, target, "nvim#14 I inserts at first non-blank", &.{ "I", ">", ESC, ":wq", CR }, "  indented\n", "  >indented\n");
    h.case(ctx, target, "nvim#15 ~ toggles case", &.{ "~", ":wq", CR }, "word\n", "Word\n");
    h.case(ctx, target, "nvim#16 delete-all writes 0 bytes", &.{ "ggVGd", ":wq", CR }, "one\ntwo\nthree\n", "");
    h.case(ctx, target, "nvim#17 * jumps to next occurrence", &.{ "*x", ":wq", CR }, "foo bar foo\n", "foo bar oo\n");
    h.case(ctx, target, "nvim#18 3x clamps at EOL", &.{ "3x", ":wq", CR }, "abc\n", "\n");
    h.case(ctx, target, "nvim#19 df<space>", &.{ "df ", ":wq", CR }, "a b c d\n", "b c d\n");
    h.case(ctx, target, "nvim#20 f( then ci( from the paren", &.{ "f(ci(", "X", ESC, ":wq", CR }, "foo(bar)\n", "foo(X)\n");
    h.case(ctx, target, "nvim#21 daw + P round-trips", &.{ "dawP", ":wq", CR }, "one two\n", "one two\n");
    h.case(ctx, target, "nvim#22 visual U uppercases selection", &.{ "veU", ":wq", CR }, "hello world\n", "HELLO world\n");
    h.case(ctx, target, "nvim#23 dw then dot at new position", &.{ "dw.", ":wq", CR }, "abc def ghi\n", "ghi\n");
    h.case(ctx, target, "nvim#24 ddp swaps lines", &.{ "ddp", ":wq", CR }, "x\ny\nz\n", "y\nx\nz\n");
    h.case(ctx, target, "nvim#25 w then cw on second word", &.{ "wcw", "ZZZ", ESC, ":wq", CR }, "aaa bbb\n", "aaa ZZZ\n");

    // :s substitution — expected results generated by the same headless nvim
    // (patterns chosen to mean the same thing in vim magic and zedit's modern
    // regex syntax).
    h.case(ctx, target, "nvim#s1 :%s g flag replaces all", &.{ ":%s/foo/bar/g\r", ":wq", CR }, "foo foo\nxfoo\n", "bar bar\nxbar\n");
    h.case(ctx, target, "nvim#s2 :s current line, first only", &.{ ":s/o/0/\r", ":wq", CR }, "foo\nfoo\n", "f0o\nfoo\n");
    h.case(ctx, target, "nvim#s3 :2,3s range", &.{ ":2,3s/a/X/g\r", ":wq", CR }, "aa\naa\naa\naa\n", "aa\nXX\nXX\naa\n");
    h.case(ctx, target, "nvim#s4 dot metachar", &.{ ":%s/b.d/X/g\r", ":wq", CR }, "bad bed\nbid\n", "X X\nX\n");
    h.case(ctx, target, "nvim#s5 anchor ^ prefixes lines", &.{ ":%s/^/> /\r", ":wq", CR }, "a\nb\n", "> a\n> b\n");
    h.case(ctx, target, "nvim#s6 i flag ignores case", &.{ ":%s/FOO/x/gi\r", ":wq", CR }, "FOO foo\n", "x x\n");
    h.case(ctx, target, "nvim#s7 character classes", &.{ ":%s/[0-9][0-9]*/N/g\r", ":wq", CR }, "a1 b22 c333\n", "aN bN cN\n");
    h.case(ctx, target, "nvim#s8 no match leaves file unchanged", &.{ ":%s/xyz/Q/g\r", ":wq", CR }, "no match here\n", "no match here\n");

    // Jumplist (Ctrl-o = \x0f back, Ctrl-i = Tab forward) — nvim-verified.
    h.case(ctx, target, "nvim#j1 G then Ctrl-o returns", &.{ "G\x0fx", ":wq", CR }, "aaa\nbbb\nccc\nddd\neee\n", "aa\nbbb\nccc\nddd\neee\n");
    h.case(ctx, target, "nvim#j2 search then Ctrl-o returns to origin", &.{ "/ddd\r\x0fx", ":wq", CR }, "aaa\nbbb\nccc\nddd\neee\n", "aa\nbbb\nccc\nddd\neee\n");
    h.case(ctx, target, "nvim#j3 Ctrl-o then Ctrl-i goes forward again", &.{ "G\x0f\tx", ":wq", CR }, "aaa\nbbb\nccc\nddd\neee\n", "aaa\nbbb\nccc\nddd\nee\n");

    // Autoindent (nvim has 'autoindent' on by default; ours matches).
    h.case(ctx, target, "nvim#a1 o inherits indent", &.{ "obar", ESC, ":wq", CR }, "    foo\n", "    foo\n    bar\n");
    h.case(ctx, target, "nvim#a2 O inherits indent", &.{ "Obar", ESC, ":wq", CR }, "    foo\n", "    bar\n    foo\n");
    h.case(ctx, target, "nvim#a3 Enter inherits indent", &.{ "A\rbar", ESC, ":wq", CR }, "    foo\n", "    foo\n    bar\n");
    h.case(ctx, target, "nvim#a4 blank o-line is stripped on Esc", &.{ "o", ESC, ":wq", CR }, "    foo\n", "    foo\n\n");
    h.case(ctx, target, "nvim#a5 blank intermediate stripped, indent carries", &.{ "A\r\rbar", ESC, ":wq", CR }, "    foo\n", "    foo\n\n    bar\n");
    h.case(ctx, target, "nvim#a6 Enter mid-line moves tail with indent", &.{ "fbi\r", ESC, ":wq", CR }, "    foo bar\n", "    foo \n    bar\n");
    h.case(ctx, target, "nvim#a7 cc keeps the indent", &.{ "ccbar", ESC, ":wq", CR }, "    foo\n", "    bar\n");
    h.case(ctx, target, "nvim#a8 tab indent copied verbatim", &.{ "obar", ESC, ":wq", CR }, "\tfoo\n", "\tfoo\n\tbar\n");
    h.case(ctx, target, "nvim#a9 blank Enter-line stripped on Esc", &.{ "A\r", ESC, ":wq", CR }, "    foo\n", "    foo\n\n");

    // Counted find-char: `[count]f/t/F/T` and `[count];`. Ground truth from
    // headless nvim on "alpha beta gamma alpha beta" — vim counts occurrences
    // and fails the motion outright when there are too few.
    const ff = "alpha beta gamma alpha beta\n";
    h.case(ctx, target, "nvim#f1 3fa lands on the third a", &.{ "3fa", "x", ":wq", CR }, ff, "alpha beta gmma alpha beta\n");
    h.case(ctx, target, "nvim#f2 2ta stops before the second a", &.{ "2ta", "x", ":wq", CR }, ff, "alpha bea gamma alpha beta\n");
    h.case(ctx, target, "nvim#f3 d3fa deletes through the third a", &.{ "d3fa", ":wq", CR }, ff, "mma alpha beta\n");
    h.case(ctx, target, "nvim#f4 2; repeats the find twice", &.{ "fa", "2;", "x", ":wq", CR }, ff, "alpha beta gmma alpha beta\n");
    h.case(ctx, target, "nvim#f5 $3Fa searches backwards by count", &.{ "$", "3Fa", "x", ":wq", CR }, ff, "alpha beta gamm alpha beta\n");
    h.case(ctx, target, "nvim#f6 a count past the last match does nothing", &.{ "9fa", "x", ":wq", CR }, ff, "lpha beta gamma alpha beta\n");

    // The undo tree: `g-`/`g+` walk states in the order they were made, so a
    // change stranded by undo-then-edit is still reachable. Ground truth from
    // headless nvim on "one" with the same keys.
    const ut = "one\n";
    h.case(ctx, target, "nvim#u1 u returns to the state before the insert", &.{ "IA", ESC, "u", ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u2 editing after an undo replaces the redo", &.{ "IA", ESC, "u", "IB", ESC, ":wq", CR }, ut, "Bone\n");
    h.case(ctx, target, "nvim#u3 g- reaches the abandoned branch", &.{ "IA", ESC, "u", "IB", ESC, "g-", ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u4 g- again reaches the original", &.{ "IA", ESC, "u", "IB", ESC, "g-", "g-", ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u5 g+ walks back forward in time", &.{ "IA", ESC, "u", "IB", ESC, "g-", "g-", "g+", ":wq", CR }, ut, "Aone\n");

    // `:earlier` / `:later`, counted in changes and in time. Ground truth from
    // real nvim driven through a pty (running the keys as `-c` arguments joins
    // the two inserts into one undo block and hides the difference).
    h.case(ctx, target, "nvim#u6 :earlier 1 steps back one change", &.{ "IA", ESC, "IB", ESC, ":earlier 1", CR, ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u7 :earlier 2 steps back two", &.{ "IA", ESC, "IB", ESC, ":earlier 2", CR, ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u8 :later 1 comes forward again", &.{ "IA", ESC, "IB", ESC, ":earlier 2", CR, ":later 1", CR, ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u9 :earlier 1h clamps to the oldest state", &.{ "IA", ESC, "IB", ESC, ":earlier 1h", CR, ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u10 :later 1h clamps to the newest", &.{ "IA", ESC, "IB", ESC, ":earlier 1h", CR, ":later 1h", CR, ":wq", CR }, ut, "BAone\n");

    // `:earlier Nf` / `:later Nf` count file writes, not changes. Ground truth
    // from real nvim through a pty: write, edit, write, edit, then walk back.
    const wr = &[_][]const u8{ "IA", ESC, ":w", CR, "IB", ESC, ":w", CR, "IC", ESC };
    h.case(ctx, target, "nvim#u11 :earlier 1f returns to the last write", wr ++ &[_][]const u8{ ":earlier 1f", CR, ":wq", CR }, ut, "BAone\n");
    h.case(ctx, target, "nvim#u12 :earlier 2f goes back two writes", wr ++ &[_][]const u8{ ":earlier 2f", CR, ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u13 :earlier 3f clamps past the first write", wr ++ &[_][]const u8{ ":earlier 3f", CR, ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u14 :later 1f comes forward a write", wr ++ &[_][]const u8{ ":earlier 2f", CR, ":later 1f", CR, ":wq", CR }, ut, "BAone\n");
    h.case(ctx, target, "nvim#u15 :earlier 1f with no writes goes to the start", &.{ "IA", ESC, "IB", ESC, ":earlier 1f", CR, ":wq", CR }, ut, "one\n");

    // Visual-mode "around" objects — nvim-verified on "x = add(a, b)".
    const va = "x = add(a, b)\n";
    h.case(ctx, target, "nvim#v1 va( takes the brackets", &.{ "fa", "va(d", ":wq", CR }, va, "x = add\n");
    h.case(ctx, target, "nvim#v2 vi( keeps them", &.{ "fa", "vi(d", ":wq", CR }, va, "x = add()\n");
    h.case(ctx, target, "nvim#v3 vaw takes the word and its space", &.{ "fa", "vawd", ":wq", CR }, va, "x =(a, b)\n");
    h.case(ctx, target, "nvim#v4 vaW takes the whole WORD", &.{ "fa", "vaWd", ":wq", CR }, va, "x = b)\n");

    // Command-line history (Up = \x1b[A, Down = \x1b[B) — nvim-verified.
    // ':' Up recalls the last ex command; Enter replays it.
    h.case(ctx, target, "nvim#h1 : Up replays last command", &.{ ":s/a/X/\r", "j", ":", "\x1b[A", "\r", ":wq", CR }, "aa\naa\n", "Xa\nXa\n");
    // Up filters by the typed prefix: ':s' skips the ':2' entry.
    h.case(ctx, target, "nvim#h2 Up filters by typed prefix", &.{ ":s/a/X/\r", ":2\r", ":s", "\x1b[A", "\r", ":wq", CR }, "aa\naa\naa\n", "Xa\nXa\naa\n");
    // '/' has its own history; Up recalls the last pattern.
    h.case(ctx, target, "nvim#h3 / Up recalls last search", &.{ "/alpha\r", "gg", "/", "\x1b[A", "\r", "x", ":wq", CR }, "one\nalpha\ntwo\nalpha\n", "one\nlpha\ntwo\nalpha\n");
    // Down past the newest entry restores the typed-but-unrun line.
    h.case(ctx, target, "nvim#h4 Down restores the typed line", &.{ ":s/a/X/\r", "j", ":s/a/Y/", "\x1b[A", "\x1b[B", "\r", ":wq", CR }, "aa\naa\n", "Xa\nYa\n");
    // :qa with unsaved changes refuses (nvim E37); the :wq still writes.
    h.case(ctx, target, "nvim#h5 :qa refuses unsaved changes", &.{ "x", ":qa\r", ":wq", CR }, "aa\n", "a\n");

    // Mid-line command-line editing (Left/Right/Home/End/Ctrl-b/Ctrl-e move a
    // cursor within the line; typing inserts, backspace deletes before it).
    // Every expectation generated by driving real nvim through a tmux pty and
    // reading the file it saved, e.g. e1's probe: `:s/a/XY/` Left Left Left
    // `Z` CR on "ab" left the file "ZXYb" — the Z landed before the X.
    h.case(ctx, target, "nvim#e1 Left then typing inserts before the cursor", &.{ ":s/a/XY/", "\x1b[D\x1b[D\x1b[D", "Z", "\r", ":wq", CR }, "ab\n", "ZXYb\n");
    // Probe: `:s/a/X/` Home `2` -> ":2s/a/X/" (the 2 landed at column 0).
    h.case(ctx, target, "nvim#e2 Home jumps to the start of the line", &.{ ":s/a/X/", "\x1b[H", "2", "\r", ":wq", CR }, "aa\naa\n", "aa\nXa\n");
    // Probe: `:s/aXb/Y/` Left x4 BS -> ":s/ab/Y/" (deleted the char before the cursor).
    h.case(ctx, target, "nvim#e3 backspace deletes before the cursor", &.{ ":s/aXb/Y/", "\x1b[D\x1b[D\x1b[D\x1b[D", "\x7f", "\r", ":wq", CR }, "ab\n", "Y\n");
    // Probe: `:s/a/Q/` Left Left Right `R` -> ":s/a/QR/" (Right moved right mid-line).
    h.case(ctx, target, "nvim#e4 Right moves the cursor right", &.{ ":s/a/Q/", "\x1b[D\x1b[D", "\x1b[C", "R", "\r", ":wq", CR }, "ab\n", "QRb\n");
    // Probe: `:s/a/W` Left Left End `/` -> ":s/a/W/" (End jumped to end-of-line).
    h.case(ctx, target, "nvim#e5 End jumps to the end of the line", &.{ ":s/a/W", "\x1b[D\x1b[D", "\x1b[F", "/", "\r", ":wq", CR }, "ab\n", "Wb\n");
    // Probes: Ctrl-b / Ctrl-e are vim's c_CTRL-B / c_CTRL-E (start / end).
    h.case(ctx, target, "nvim#e6 Ctrl-b to the beginning", &.{ ":s/a/X/", "\x02", "2", "\r", ":wq", CR }, "aa\naa\n", "aa\nXa\n");
    h.case(ctx, target, "nvim#e7 Ctrl-e to the end", &.{ ":s/a/W", "\x1b[D\x1b[D", "\x05", "/", "\r", ":wq", CR }, "ab\n", "Wb\n");
    // Probe: Home BS `2` -> ":2s/a/X/" — backspace at column 0 of a NON-empty
    // line is a no-op in nvim (it neither deletes nor cancels the cmdline).
    h.case(ctx, target, "nvim#e8 backspace at column 0 is a no-op", &.{ ":s/a/X/", "\x1b[H", "\x7f", "2", "\r", ":wq", CR }, "aa\naa\n", "aa\nXa\n");
    // Probe: `:` Up recalls ":s/a/X/" with the cursor at END of line, so the
    // typed `g` appends -> ":s/a/X/g" replaced both a's on line 2.
    h.case(ctx, target, "nvim#e9 history recall puts the cursor at the end", &.{ ":s/a/X/\r", "j", ":", "\x1b[A", "g", "\r", ":wq", CR }, "aa\naa\n", "Xa\nXX\n");
    // Probe: `:s/a/XY/` Left x3 CR -> "XYb", not "Xb" — Enter runs the WHOLE
    // line, never just the part before the cursor.
    h.case(ctx, target, "nvim#e10 Enter mid-line runs the whole line", &.{ ":s/a/XY/", "\x1b[D\x1b[D\x1b[D", "\r", ":wq", CR }, "ab\n", "XYb\n");

    // Command-line editing keys: Delete, c_CTRL-W, c_CTRL-U, c_CTRL-R and Tab
    // with the cursor mid-line. Every expectation below came out of real nvim
    // (`-u NONE -i NONE -n --noplugin`) driven through a tmux pty with exactly
    // these keys, reading back the file it saved.
    const DEL = "\x1b[3~";
    const LEFT = "\x1b[D";
    const HOME = "\x1b[H";
    const CTRLW = "\x17";
    const CTRLU = "\x15";
    const CTRLR = "\x12";

    // <Del> takes the character *under* the cursor…
    h.case(ctx, target, "nvim#d1 Delete under the cursor", &.{ ":s/aXb/Y/", LEFT ** 5, DEL, CR, ":wq", CR }, "ab\n", "Y\n");
    h.case(ctx, target, "nvim#d2 two Deletes", &.{ ":s/aXYb/Q/", LEFT ** 6, DEL, DEL, CR, ":wq", CR }, "ab\n", "Q\n");
    // …but at end-of-line the one *before* it (probe: ":s/a/XY" + Del ran
    // ":s/a/X", so the Y went), and at column 0 the first character.
    h.case(ctx, target, "nvim#d3 Delete at end-of-line deletes the char before", &.{ ":s/a/XY", DEL, CR, ":wq", CR }, "ab\n", "Xb\n");
    h.case(ctx, target, "nvim#d4 Delete at column 0", &.{ ":s/a/X/", HOME, DEL, "s", CR, ":wq", CR }, "ab\n", "Xb\n");
    // On an empty line it cancels the command line, exactly as backspace does:
    // the following 'x' is a normal-mode key, so it deletes the 'a'.
    h.case(ctx, target, "nvim#d5 Delete on an empty command line cancels", &.{ ":", DEL, "x", ":wq", CR }, "ab\n", "b\n");

    // c_CTRL-W erases the word before the cursor; the whitespace in front of
    // it goes too ("…/X/ foo  " -> "…/X/ "), a punctuation run is its own word
    // ("…/g!!!" -> "…/g"), and mid-line the tail stays put.
    h.case(ctx, target, "nvim#w1 Ctrl-W erases the word before the cursor", &.{ ":s/a/X/junk", CTRLW, CR, ":wq", CR }, "ab\n", "Xb\n");
    h.case(ctx, target, "nvim#w2 Ctrl-W skips (and takes) trailing blanks", &.{ ":s/a/X/ foo  ", CTRLW, CR, ":wq", CR }, "ab\n", "Xb\n");
    h.case(ctx, target, "nvim#w3 Ctrl-W twice", &.{ ":s/a/X/ one two", CTRLW, CTRLW, CR, ":wq", CR }, "ab\n", "Xb\n");
    h.case(ctx, target, "nvim#w4 Ctrl-W takes a punctuation run alone", &.{ ":%s/a/X/g!!!", CTRLW, CR, ":wq", CR }, "aa\naa\n", "XX\nXX\n");
    h.case(ctx, target, "nvim#w5 Ctrl-W mid-line keeps the tail", &.{ ":s/JUNKa/X/", LEFT ** 4, CTRLW, CR, ":wq", CR }, "ab\n", "Xb\n");
    h.case(ctx, target, "nvim#w6 Ctrl-W at column 0 is a no-op", &.{ ":s/a/X/", HOME, CTRLW, CR, ":wq", CR }, "ab\n", "Xb\n");

    // c_CTRL-U erases from the start of the line to the cursor — not the whole
    // line: with the cursor after "JUNK" the rest still runs.
    h.case(ctx, target, "nvim#u16 Ctrl-U erases the typed line", &.{ ":junk", CTRLU, "s/a/X/", CR, ":wq", CR }, "ab\n", "Xb\n");
    h.case(ctx, target, "nvim#u17 Ctrl-U mid-line keeps the tail", &.{ ":JUNKs/a/X/", LEFT ** 6, CTRLU, CR, ":wq", CR }, "ab\n", "Xb\n");
    h.case(ctx, target, "nvim#u18 Ctrl-U at column 0 is a no-op", &.{ ":s/a/X/", HOME, CTRLU, CR, ":wq", CR }, "ab\n", "Xb\n");

    // c_CTRL-R inserts a register at the cursor; an unknown or empty register
    // inserts nothing and swallows the key (the line runs as typed).
    h.case(ctx, target, "nvim#r1 Ctrl-R inserts a named register", &.{ "\"ayiw", ":s/", CTRLR, "a", "/X/", CR, ":wq", CR }, "hello world\n", "X world\n");
    h.case(ctx, target, "nvim#r2 Ctrl-R inserts the unnamed register", &.{ "yiw", ":s/", CTRLR, "\"", "/X/", CR, ":wq", CR }, "hello world\n", "X world\n");
    h.case(ctx, target, "nvim#r3 Ctrl-R with an invalid register inserts nothing", &.{ ":s/hello/X/", CTRLR, "$", CR, ":wq", CR }, "hello world\n", "X world\n");
    h.case(ctx, target, "nvim#r4 Ctrl-R with an empty register inserts nothing", &.{ ":s/hello/X/", CTRLR, "z", CR, ":wq", CR }, "hello world\n", "X world\n");
    h.case(ctx, target, "nvim#r5 Ctrl-R mid-line inserts at the cursor", &.{ "\"ayiw", ":s//X/", LEFT ** 3, CTRLR, "a", CR, ":wq", CR }, "hello world\n", "X world\n");
    h.case(ctx, target, "nvim#r6 the line stays editable after a register insert", &.{ "\"ayiw", ":s/", CTRLR, "a", "Q/X/", LEFT ** 4, DEL, CR, ":wq", CR }, "hello world\n", "X world\n");

    // Tab completes only the text BEFORE the cursor and keeps the tail: with
    // the cursor after "earlie" the count " 2" survives, so ":earlier 2" runs
    // and both changes come off (probe T10). Completing with no tail after it
    // is ":earlier" — one change (probe T12) — which is also what zedit does
    // when a completion swallows the rest of the line.
    h.case(ctx, target, "nvim#t1 Tab mid-line keeps the tail", &.{ "IA", ESC, "IB", ESC, ":earlie 2", LEFT ** 2, "\t", CR, ":wq", CR }, "one\n", "one\n");
    h.case(ctx, target, "nvim#t2 …against Tab with no tail", &.{ "IA", ESC, "IB", ESC, ":earlie", "\t", CR, ":wq", CR }, "one\n", "Aone\n");

    // A command line wider than the terminal row wraps onto further rows in
    // both editors (nvim grows the command-line area upward, probe H1) and
    // still runs as one command.
    const long_rep = "0123456789" ** 9; // 90 characters: wider than the 80-column pty
    h.case(ctx, target, "nvim#t3 a wrapped command line runs as one command", &.{ ":s/a/" ++ long_rep ++ "/", CR, ":wq", CR }, "ab\n", long_rep ++ "b\n");

    // Paragraph motions and text objects ({ } ip ap) — nvim-verified.
    const P2 = "aaa\nbbb\n\nccc\nddd\n";
    const P3 = "aaa\n\nbbb\n\nccc\n";
    h.case(ctx, target, "nvim#p1 } lands on the empty line", &.{ "}x", ":wq", CR }, P2, P2);
    h.case(ctx, target, "nvim#p2 d} from col 0 is linewise", &.{ "d}", ":wq", CR }, P2, "\nccc\nddd\n");
    h.case(ctx, target, "nvim#p3 d} mid-line stays charwise", &.{ "lld}", ":wq", CR }, P2, "aa\n\nccc\nddd\n");
    h.case(ctx, target, "nvim#p4 { lands on the empty line", &.{ "G{x", ":wq", CR }, P2, P2);
    h.case(ctx, target, "nvim#p5 d{ deletes back to boundary", &.{ "G$d{", ":wq", CR }, P2, "aaa\nbbb\nd\n");
    h.case(ctx, target, "nvim#p6 dip deletes the paragraph", &.{ "dip", ":wq", CR }, P2, "\nccc\nddd\n");
    h.case(ctx, target, "nvim#p7 dap takes the trailing blank", &.{ "dap", ":wq", CR }, P2, "ccc\nddd\n");
    h.case(ctx, target, "nvim#p8 dip on a blank line", &.{ "jdip", ":wq", CR }, "aaa\n\n\nbbb\n", "aaa\nbbb\n");
    h.case(ctx, target, "nvim#p9 dap on last para takes leading blank", &.{ "Gdap", ":wq", CR }, P2, "aaa\nbbb\n");
    h.case(ctx, target, "nvim#p10 vip d is linewise", &.{ "vipd", ":wq", CR }, P2, "\nccc\nddd\n");
    h.case(ctx, target, "nvim#p11 yap P round-trips", &.{ "yapP", ":wq", CR }, P3, "aaa\n\naaa\n\nbbb\n\nccc\n");
    h.case(ctx, target, "nvim#p12 2} skips a boundary", &.{ "2}x", ":wq", CR }, P3, P3);
    h.case(ctx, target, "nvim#p13 whitespace-only line is no boundary", &.{ "}x", ":wq", CR }, "aaa\n  \nbbb\n\nccc\n", "aaa\n  \nbbb\n\nccc\n");
    h.case(ctx, target, "nvim#p14 cip changes the paragraph", &.{ "cip", "XX", ESC, ":wq", CR }, P2, "XX\n\nccc\nddd\n");
    h.case(ctx, target, "nvim#p15 } at EOF clamps to last line", &.{ "}}x", ":wq", CR }, P2, "aaa\nbbb\n\nccc\ndd\n");
    h.case(ctx, target, "nvim#p16 d2ap takes two paragraphs", &.{ "d2ap", ":wq", CR }, P3, "ccc\n");

    // The cursor never sits past the last character in normal mode, so
    // commands after `$` act on the last character (regression: `$x` used to
    // do nothing and `$dh`/`$d0`/`$db` were all off by one). nvim-verified.
    h.case(ctx, target, "nvim#c1 $x deletes the last character", &.{ "$x", ":wq", CR }, "abc\n", "ab\n");
    h.case(ctx, target, "nvim#c2 $dh deletes before the last", &.{ "$dh", ":wq", CR }, "abc\n", "ac\n");
    h.case(ctx, target, "nvim#c3 $d0 keeps the last character", &.{ "$d0", ":wq", CR }, "abc\n", "c\n");
    h.case(ctx, target, "nvim#c4 $db from end of line", &.{ "$db", ":wq", CR }, "abc def\n", "abc f\n");
    h.case(ctx, target, "nvim#c5 $dF exclusive backward find", &.{ "$dFc", ":wq", CR }, "abc def\n", "abf\n");

    // Mouse (nvim `mouse=a`): a click moves the cursor, a drag selects. Every
    // expectation below came out of real nvim through a pty — see the helpers
    // at the top of this file for the coordinate mapping.
    const M = "abcdefghij\nklmnopqrst\nuvwxyz1234\n";
    // A pending operator takes the click as an exclusive charwise motion,
    // across lines and in either direction, and ignores any count.
    h.case(ctx, target, "nvim#m1 d + click is exclusive charwise", &.{ "d", click(2, 4), ":wq", CR }, M, "opqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m2 d + click backwards", &.{ "G$", "d", click(2, 2), ":wq", CR }, M, "abcdefghij\nkl4\n");
    // vim's exclusive rules: an end in column 0 becomes linewise when the
    // start was at or before its line's first non-blank, else it stops at the
    // end of the previous line.
    h.case(ctx, target, "nvim#m3 d + click at column 0 is linewise", &.{ "d", click(3, 0), ":wq", CR }, M, "uvwxyz1234\n");
    h.case(ctx, target, "nvim#m4 d mid-line + click at column 0", &.{ "ll", "d", click(3, 0), ":wq", CR }, M, "ab\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m5 y + click yanks linewise", &.{ "y", click(3, 0), "P", ":wq", CR }, M, "abcdefghij\nklmnopqrst\nabcdefghij\nklmnopqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m6 d2 + click ignores the count", &.{ "d2", click(2, 4), ":wq", CR }, M, "opqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m7 a pending count is discarded", &.{ "3", click(2, 4), "x", ":wq", CR }, M, "abcdefghij\nklmnpqrst\nuvwxyz1234\n");
    // A click ends a selection, from `v` and from `V` alike.
    h.case(ctx, target, "nvim#m8 click ends visual", &.{ "v", click(2, 4), "x", ":wq", CR }, M, "abcdefghij\nklmnpqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m9 click ends V-LINE", &.{ "V", click(2, 4), "x", ":wq", CR }, M, "abcdefghij\nklmnpqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m10 insert mode continues at the click", &.{ "i", click(2, 4), "QQQ", ESC, ":wq", CR }, M, "abcdefghij\nklmnQQQopqrst\nuvwxyz1234\n");
    // curswant keeps the *clicked* column, not the clamped one.
    h.case(ctx, target, "nvim#m11 click past EOL keeps the column for k", &.{ click(3, 39), "k", "x", ":wq", CR }, "short\nabcdefghijklmnopqrst\nxy\n", "short\nabcdefghijklmnopqrs\nxy\n");
    // A click below the last line clamps to it and keeps the column (screen
    // row 20 is a `~` row in both editors for this three-line file).
    h.case(ctx, target, "nvim#m12 click past EOF clamps to the last line", &.{ "\x1b[<0;10;20M\x1b[<0;10;20m", "x", ":wq", CR }, M, "abcdefghij\nklmnopqrst\nuvwxz1234\n");
    // Drag: the press anchors, motion extends, the selection is inclusive.
    h.case(ctx, target, "nvim#m13 drag selects from the press", &.{ press(1, 2), drag(2, 5), drag(3, 5), release(3, 5), "d", ":wq", CR }, M, "ab1234\n");
    h.case(ctx, target, "nvim#m14 a drag out of V-LINE is charwise", &.{ "V", press(1, 2), drag(2, 5), release(2, 5), "d", ":wq", CR }, M, "abqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m15 a drag to the same cell stays normal", &.{ press(2, 4), drag(2, 4), release(2, 4), "x", ":wq", CR }, M, "abcdefghij\nklmnpqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m16 the release extends the selection too", &.{ press(1, 2), drag(2, 5), release(3, 1), "d", ":wq", CR }, M, "abwxyz1234\n");
    h.case(ctx, target, "nvim#m17 a click leaves the drag selection", &.{ press(1, 2), drag(2, 5), release(2, 5), click(3, 3), "x", ":wq", CR }, M, "abcdefghij\nklmnopqrst\nuvwyz1234\n");
    // A click pushes no jumplist entry: Ctrl-o returns to `G`'s origin.
    h.case(ctx, target, "nvim#m18 a click adds no jump", &.{ "G", click(2, 4), "\x0f", "x", ":wq", CR }, M, "bcdefghij\nklmnopqrst\nuvwxyz1234\n");
    // A click past both ends reaches end-of-line, so `d` empties the line.
    h.case(ctx, target, "nvim#m19 d + click past EOL empties the line", &.{ "d", "\x1b[<0;40;10M\x1b[<0;40;10m", ":wq", CR }, "one two three\n", "\n");
    // A pending operator is consumed by the *press*; the drag and release that
    // follow it find nothing to extend and change nothing more.
    h.case(ctx, target, "nvim#m20 d + press-drag-release acts at the press", &.{ "d", press(2, 6), drag(3, 7), release(3, 7), ":wq", CR }, M, "qrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m21 y + press-drag-release yanks at the press", &.{ "y", press(2, 6), drag(3, 7), release(3, 7), "P", ":wq", CR }, M, "abcdefghij\nklmnopabcdefghij\nklmnopqrst\nuvwxyz1234\n");
    // `.` repeats an operator+click: vim's redo stores the *screen* position,
    // so the repeat re-resolves the same cell from wherever the cursor now is.
    // (Without the click in the dot capture, `.` silently repeated whatever
    // change came before it — `dl` here — instead.)
    h.case(ctx, target, "nvim#m22 . repeats an operator+click", &.{ "d", click(1, 4), "j0", ".", ":wq", CR }, M, "efgh\nklmnopqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m23 . after an earlier change repeats the click", &.{ "dl", "d", click(2, 4), ".", ":wq", CR }, M, "yz1234\n");
    // An exclusive end in column 0 of line *2* steps back to line 1 — the one
    // row where the step used to underflow and abort the editor.
    h.case(ctx, target, "nvim#m24 d + click at column 0 of line 2", &.{ "d", click(2, 0), ":wq", CR }, M, "klmnopqrst\nuvwxyz1234\n");
    // …and the line it steps back to must be the right one: with lines of
    // different lengths the span used to stop at the *previous* line's width.
    h.case(ctx, target, "nvim#m25 d + click at column 0, unequal lines", &.{ "ll", "d", click(3, 0), ":wq", CR }, "abXY\nklmnopqrst\nuvw\n", "ab\nuvw\n");
    // The same rule with no mouse at all (`}` is exclusive too), which is how
    // the underflow and the wrong-length span were reachable before clicks.
    h.case(ctx, target, "nvim#m26 d} onto a blank line 2", &.{ "d}", ":wq", CR }, "abc\n\ndef\n", "\ndef\n");
    h.case(ctx, target, "nvim#m27 d} stops at its own line's end", &.{ "jl", "d}", ":wq", CR }, "ab\nlonglongline\n\nx\n", "ab\nl\n\nx\n");
    // A click recorded in a macro replays as a click.
    h.case(ctx, target, "nvim#m28 a macro replays a click", &.{ "qa", click(3, 3), "x", "q", "@a", ":wq", CR }, M, "abcdefghij\nklmnopqrst\nuvwz1234\n");

    // Multi-click gestures: 2 = the word, 3 = the line (linewise), 4 = one
    // blockwise cell, and the fifth click starts the cycle again. The word is
    // vim's *mouse* word, which is not `iw`: punctuation goes through `%` when
    // there is an item at or after the click on that line, and otherwise
    // groups only with its own class.
    const W = "hello, world foo\n  indented text here\nfoo.bar(baz) end\n";
    const P = "abc..def(g)\na(b)cd.ef\na->b(c)\nabc<def>ghi\n";
    const G = "alpha beta gamma delta epsilon\nsecond line here now\nthird line here now\n";
    h.case(ctx, target, "nvim#m29 double click selects the word", &.{ multi(2, 1, 8), "d", ":wq", CR }, W, "hello,  foo\n  indented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m30 double click at column 0", &.{ multi(2, 1, 0), "d", ":wq", CR }, W, ", world foo\n  indented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m31 double click past EOL takes the last word", &.{ multi(2, 1, 39), "d", ":wq", CR }, W, "hello, world \n  indented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m32 double click on punctuation is not iw", &.{ multi(2, 1, 5), "d", ":wq", CR }, W, "hello world foo\n  indented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m33 double click takes a whole blank run", &.{ multi(2, 2, 0), "d", ":wq", CR }, W, "hello, world foo\nindented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m34 double click runs % from the click", &.{ multi(2, 1, 3), "d", ":wq", CR }, P, "abc\na(b)cd.ef\na->b(c)\nabc<def>ghi\n");
    h.case(ctx, target, "nvim#m35 % only looks forward", &.{ multi(2, 2, 6), "d", ":wq", CR }, P, "abc..def(g)\na(b)cdef\na->b(c)\nabc<def>ghi\n");
    h.case(ctx, target, "nvim#m36 -> reaches the pair behind it", &.{ multi(2, 3, 1), "d", ":wq", CR }, P, "abc..def(g)\na(b)cd.ef\na\nabc<def>ghi\n");
    h.case(ctx, target, "nvim#m37 <> is not a matchpair", &.{ multi(2, 4, 3), "d", ":wq", CR }, P, "abc..def(g)\na(b)cd.ef\na->b(c)\nabcdef>ghi\n");
    h.case(ctx, target, "nvim#m38 triple click selects the line", &.{ multi(3, 2, 4), "d", ":wq", CR }, M, "abcdefghij\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m39 triple click past EOL is the same line", &.{ multi(3, 2, 39), "d", ":wq", CR }, M, "abcdefghij\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m40 quadruple click selects one cell", &.{ multi(4, 2, 4), "d", ":wq", CR }, M, "abcdefghij\nklmnpqrst\nuvwxyz1234\n");
    h.case(ctx, target, "nvim#m41 a fifth click is a plain click", &.{ multi(5, 1, 8), "x", ":wq", CR }, W, "hello, wrld foo\n  indented text here\nfoo.bar(baz) end\n");
    h.case(ctx, target, "nvim#m42 a click one cell over does not chain", &.{ comptime click(1, 8) ++ click(1, 9), "x", ":wq", CR }, W, "hello, wold foo\n  indented text here\nfoo.bar(baz) end\n");
    // Dragging after a multi-click extends by whole words / lines / a block,
    // in both directions, with the clicked word always kept whole.
    h.case(ctx, target, "nvim#m43 a drag after a double click extends by words", &.{ multiHold(2, 1, 7), drag(1, 13), release(1, 13), "d", ":wq", CR }, G, "alpha  delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m44 …backwards too", &.{ multiHold(2, 1, 7), drag(1, 2), release(1, 2), "d", ":wq", CR }, G, " gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m45 …snapping to a blank run", &.{ multiHold(2, 1, 7), drag(1, 10), release(1, 10), "d", ":wq", CR }, G, "alpha gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m46 a release at the press keeps the word", &.{ multiHold(2, 1, 7), release(1, 7), "d", ":wq", CR }, G, "alpha  gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m47 a drag after a triple click is linewise", &.{ multiHold(3, 1, 7), drag(2, 5), release(2, 5), "d", ":wq", CR }, G, "third line here now\n");
    h.case(ctx, target, "nvim#m48 a drag after a quadruple click is a block", &.{ multiHold(4, 1, 7), drag(3, 13), release(3, 13), "d", ":wq", CR }, G, "alpha bma delta epsilon\nsecond re now\nthird le now\n");
    // Insert Visual: a gesture begun in insert mode returns to insert —
    // whether it ends with Esc, with an operator, or with a plain click.
    h.case(ctx, target, "nvim#m49 insert + double click, Esc resumes insert", &.{ "i", multi(2, 1, 7), ESC, "QQ", ESC, ":wq", CR }, G, "alpha betQQa gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m50 insert + drag, d resumes insert", &.{ "i", press(1, 2), drag(1, 8), release(1, 8), "d", "QQ", ESC, ":wq", CR }, G, "alQQa gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m51 insert + triple click keeps the clicked column", &.{ "i", multi(3, 1, 7), ESC, "QQ", ESC, ":wq", CR }, G, "alpha bQQeta gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m52 a macro replays a double click", &.{ "qa", multi(2, 1, 7), "x", "q", "@a", ":wq", CR }, G, "alpha   delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m53 a click inside Insert Visual keeps typing", &.{ "i", multi(2, 1, 7), click(2, 3), "QQ", ESC, ":wq", CR }, G, "alpha beta gamma delta epsilon\nsecQQond line here now\nthird line here now\n");
    // Every press decides the click count, wherever it lands — vim works it
    // out in the input layer, before the click is routed anywhere — so a press
    // on chrome breaks a chain in two. The command line is the last screen row
    // in both editors (24), and a press there is inert in both.
    const cmdrow = "\x1b[<0;40;24M\x1b[<0;40;24m";
    h.case(ctx, target, "nvim#m54 a press on the command line breaks the chain", &.{ comptime click(1, 7) ++ cmdrow ++ click(1, 7), "x", ":wq", CR }, G, "alpha bta gamma delta epsilon\nsecond line here now\nthird line here now\n");
    h.case(ctx, target, "nvim#m55 …and does not just delay it", &.{ comptime click(1, 7) ++ click(1, 7) ++ cmdrow ++ click(1, 7), "x", ":wq", CR }, G, "alpha bta gamma delta epsilon\nsecond line here now\nthird line here now\n");

    // Regex `/` search: the pattern jumps, then x edits at the match.
    h.case(ctx, target, "regex / search jumps to match", &.{ "/b.d\r", "x", ":wq", CR }, "xxx\nbad\n", "xxx\nad\n");
    // Capture groups in the replacement swap two words.
    h.case(ctx, target, "capture groups in :s replacement", &.{ ":%s/(\\w+) (\\w+)/\\2 \\1/\r", ":wq", CR }, "one two\n", "two one\n");

    blockPaste(ctx);
    blockInsert(ctx);
    dotAndMacros(ctx);
}

/// Blockwise registers and their rectangular paste. Every expectation below
/// came out of headless nvim driven through the pty prober, and together they
/// pin the whole model: `p` inserts after the cursor cell and `P` at it (both
/// at column 0 on an empty line); a line too short to reach that column is
/// padded with spaces; a register line is squared up to the block's width only
/// when something follows it (the line's own tail, or another repetition of a
/// count); the buffer grows new lines when the block outlasts it; and the
/// cursor lands on the rectangle's first cell.
fn blockPaste(ctx: *h.Ctx) void {
    const abc = "abc\ndef\nghi\n";
    const two = "11\n22\nab\nc\n";
    h.case(ctx, target, "nvim#bp1 p puts the block after the cursor cell", &.{ CV ++ "jy", "ll", "p", ":wq", CR }, abc, "abca\ndefd\nghi\n");
    h.case(ctx, target, "nvim#bp2 P puts it at the cursor cell", &.{ CV ++ "jy", "ll", "P", ":wq", CR }, abc, "abac\ndedf\nghi\n");
    h.case(ctx, target, "nvim#bp3 a line too short for the column is padded", &.{ CV ++ "jly", "jj$", "p", ":wq", CR }, two, "11\n22\nab11\nc 22\n");
    h.case(ctx, target, "nvim#bp4 P at column 0", &.{ CV ++ "jly", "jj0", "P", ":wq", CR }, "11\n22\nab\ncd\n", "11\n22\n11ab\n22cd\n");
    h.case(ctx, target, "nvim#bp5 the block grows the file past its end", &.{ CV ++ "jly", "G$", "p", ":wq", CR }, "11\n22\nzz\n", "11\n22\nzz11\n  22\n");
    h.case(ctx, target, "nvim#bp6 …P too", &.{ CV ++ "jly", "G$", "P", ":wq", CR }, "11\n22\nzz\n", "11\n22\nz11z\n 22\n");
    h.case(ctx, target, "nvim#bp7 a three-row block past the end", &.{ CV ++ "jjly", "G$", "p", ":wq", CR }, "11\n22\n33\nq\n", "11\n22\n33\nq11\n 22\n 33\n");
    h.case(ctx, target, "nvim#bp8 a count lays the block side by side", &.{ CV ++ "jly", "jj0", "3p", ":wq", CR }, "ab\ncd\nxy\nzw\n", "ab\ncd\nxabababy\nzcdcdcdw\n");
    h.case(ctx, target, "nvim#bp9 an empty register line pads out when text follows", &.{ "l" ++ CV ++ "jy", "jj0", "p", ":wq", CR }, "ab\nc\nxxxx\nyyyy\n", "ab\nc\nxbxxx\ny yyy\n");
    h.case(ctx, target, "nvim#bp10 …but not at end-of-line, which leaves the pad bare", &.{ CV ++ "jly", "jj$", "p", ":wq", CR }, "11\n\nabcdef\nx\n", "11\n\nabcdef1\nx     \n");
    h.case(ctx, target, "nvim#bp11 the cursor lands on the block's first cell", &.{ CV ++ "jly", "jj0", "p", "x", ":wq", CR }, "11\n22\nabcd\nefgh\n", "11\n22\na1bcd\ne22fgh\n");
    h.case(ctx, target, "nvim#bp12 …after P as well", &.{ CV ++ "jly", "jjl", "P", "x", ":wq", CR }, "11\n22\nabcd\nefgh\n", "11\n22\na1bcd\ne22fgh\n");
    h.case(ctx, target, "nvim#bp13 the block goes into the middle of a taller file", &.{ CV ++ "jly", "jjl", "p", ":wq", CR }, "11\n22\naaaa\nbbbb\ncccc\ndddd\n", "11\n22\naa11aa\nbb22bb\ncccc\ndddd\n");
    h.case(ctx, target, "nvim#bp14 an empty line takes the block at column 0", &.{ CV ++ "jly", "G0", "p", ":wq", CR }, "11\n22\n\n", "11\n22\n11\n22\n");
    // A blockwise *delete* fills the register just as a yank does — `x` is `d`.
    h.case(ctx, target, "nvim#bp15 a blockwise d fills the register", &.{ "l" ++ CV ++ "jd", "G$", "p", ":wq", CR }, abc, "ac\ndf\nghib\n   e\n");
    h.case(ctx, target, "nvim#bp16 a blockwise x fills it the same way", &.{ "l" ++ CV ++ "jx", "G$", "p", ":wq", CR }, abc, "ac\ndf\nghib\n   e\n");
    // `$` makes the block ragged: it follows each line's own end, and the
    // register keeps no fixed right edge — so it pastes ragged unless a tail
    // or a further repetition needs it squared up.
    h.case(ctx, target, "nvim#bp17 a $ block pastes ragged", &.{ CV ++ "j$y", "jj0", "p", ":wq", CR }, "abcd\nef\nX\nY\n", "abcd\nef\nXabcd\nYef\n");
    h.case(ctx, target, "nvim#bp18 …squared up for all but the last repetition", &.{ CV ++ "j$y", "jj0", "2p", ":wq", CR }, "abcd\nef\nX\nY\n", "abcd\nef\nXabcdabcd\nYef  ef\n");
    h.case(ctx, target, "nvim#bp19 …and its width still pads a tail", &.{ CV ++ "j$y", "jj0", "p", ":wq", CR }, "abcd\nef\nQQQQ\nRRRR\n", "abcd\nef\nQabcdQQQ\nRef  RRR\n");
    h.case(ctx, target, "nvim#bp20 a $ block d fills the register too", &.{ "l" ++ CV ++ "j$d", "G$", "p", ":wq", CR }, "abcd\nef\nghij\nQQ\nRR\n", "a\ne\nghij\nQQ\nRRbcd\n  f\n");
    // A block may reach one column past a short line's end (vim's blockwise
    // rule), and that width travels with the register.
    h.case(ctx, target, "nvim#bp21 a block one past a short line keeps its width", &.{ CV ++ "lll", "y", "j0", "p", ":wq", CR }, "ab\nQQQQ\n", "ab\nQab QQQ\n");
    h.case(ctx, target, "nvim#bp22 j keeps the goal column across an empty line", &.{ "l" ++ CV ++ "jj", "y", "3j0", "p", ":wq", CR }, "abcd\n\nefgh\nZZZZ\nWWWW\nVVVV\n", "abcd\n\nefgh\nZbZZZ\nW WWW\nVfVVV\n");
    // The register kind is per write: a block yank replaces an earlier
    // linewise one, and `"a` picks the register in visual mode as in normal.
    h.case(ctx, target, "nvim#bp23 a block yank overrides an earlier linewise one", &.{ "yy", CV ++ "jly", "G0", "p", ":wq", CR }, "ab\ncd\nzz\n", "ab\ncd\nzabz\n cd\n");
    h.case(ctx, target, "nvim#bp24 a blockwise register round-trips through \"a", &.{ CV ++ "jl", "\"ay", "jj0", "\"ap", ":wq", CR }, "11\n22\nzz\nyy\n", "11\n22\nz11z\ny22y\n");
    h.case(ctx, target, "nvim#bp25 u undoes the whole rectangle", &.{ CV ++ "jly", "jj0", "p", "u", ":wq", CR }, "11\n22\nabcd\nefgh\n", "11\n22\nabcd\nefgh\n");
    // A line stopping *before* the block's left edge does not yank as nothing:
    // vim records the block's width in spaces there, so the rectangle survives
    // a paste at end-of-line, where nothing follows to square it up. (Such a
    // row is always interior — the endpoint sitting on a short line is what
    // clamped `left` to begin with, so a row ending exactly at the edge, in
    // bp31, must stay empty.)
    const gap8 = "abcdefgh\nZ\nabcdefgh\nQQ\n";
    h.case(ctx, target, "nvim#bp26 a row short of the left edge yanks spaces", &.{ "ll" ++ CV ++ "jjlly", "G$", "p", ":wq", CR }, gap8, "abcdefgh\nZ\nabcdefgh\nQQcde\n     \n  cde\n");
    h.case(ctx, target, "nvim#bp27 …from a blockwise d as well", &.{ "ll" ++ CV ++ "jjlld", "G$", "p", ":wq", CR }, gap8, "abfgh\nZ\nabfgh\nQQcde\n     \n  cde\n");
    h.case(ctx, target, "nvim#bp28 …and one wider still under $", &.{ "ll" ++ CV ++ "jj$y", "G$", "p", ":wq", CR }, gap8, "abcdefgh\nZ\nabcdefgh\nQQcdefgh\n         \n  cdefgh\n");
    h.case(ctx, target, "nvim#bp29 …repeated whole by a count", &.{ "ll" ++ CV ++ "jjly", "G$", "3p", ":wq", CR }, "abcdef\nZ\nabcdef\nQQ\n", "abcdef\nZ\nabcdef\nQQcdcdcd\n        \n  cdcdcd\n");
    h.case(ctx, target, "nvim#bp30 …and wider than a $ block's own width", &.{ "ll" ++ CV ++ "jj$y", "3j0", "P", ":wq", CR }, "abcdefgh\nZ\nabcdefgh\nQQQQ\nRRRR\nSSSS\n", "abcdefgh\nZ\nabcdefgh\ncdefghQQQQ\n       RRRR\ncdefghSSSS\n");
    h.case(ctx, target, "nvim#bp31 a row ending exactly at the edge stays empty", &.{ "ll" ++ CV ++ "jjlly", "G$", "p", ":wq", CR }, "abcdefgh\nabcdefgh\nZ\nQQ\n", "abcdefgh\nabcdefgh\nZ\nQQbc\n  bc\n  \n");
    // `"A` appends: the register keeps the kind it had — a rectangle gains a
    // row at its own width — unless the addition is linewise, which overrides.
    h.case(ctx, target, "nvim#bp32 \"A adds a row to a blockwise register", &.{ CV ++ "jl", "\"ay", "jj0", "\"Ay$", "j0", "\"ap", ":wq", CR }, "ab\ncd\nZZZZZZ\nYYYY\nWWWW\nVVVV\n", "ab\ncd\nZZZZZZ\nYabYYY\nWcdWWW\nVZZZZZZVVV\n");
    h.case(ctx, target, "nvim#bp33 …but a linewise \"A overrides the kind", &.{ CV ++ "jl", "\"ay", "jj", "\"Ayy", "G0", "\"ap", ":wq", CR }, "ab\ncd\nZZZZ\nYYYY\n", "ab\ncd\nZZZZ\nYYYY\nab\ncd\nZZZZ\n");
    // The block's right edge is the *last* cell of the character an endpoint
    // sits on, so a double-width character — or a tab — is covered whole.
    h.case(ctx, target, "nvim#bp34 a block ending on a wide char covers it", &.{ CV ++ "jld", ":wq", CR }, "漢字ab\n漢字cd\n", "ab\ncd\n");
    h.case(ctx, target, "nvim#bp35 …and pastes it back whole", &.{ CV ++ "jly", "jj0", "p", ":wq", CR }, "漢字\n日本\nxxxxxx\nyyyyyy\n", "漢字\n日本\nx漢字xxxxx\ny日本yyyyy\n");
    h.case(ctx, target, "nvim#bp36 …a wide char one cell in, too", &.{ "l" ++ CV ++ "jy", "jj0", "P", ":wq", CR }, "a漢b\nc漢d\nQQQQ\nRRRR\n", "a漢b\nc漢d\n漢QQQQ\n漢RRRR\n");
    h.case(ctx, target, "nvim#bp37 …and a tab at the edge", &.{ "ll" ++ CV ++ "jy", "jj0", "p", ":wq", CR }, "abcd\n\tZ\nQQQQQQ\nRRRRRR\n", "abcd\n\tZ\nQabcdQQQQQ\nR\tRRRRR\n");
}

/// Blockwise `I` / `A` / `c` on lines that do not reach the block, which is
/// where vim is deliberately asymmetric: `A` pads a short line out with
/// spaces, while `I` and `c` skip it entirely. All nvim-verified.
fn blockInsert(ctx: *h.Ctx) void {
    const gap = "abcd\n\nefgh\n";
    const ragged = "abcd\nef\nghijkl\n";
    h.case(ctx, target, "nvim#bi1 A pads a line short of the append column", &.{ "l" ++ CV ++ "jj", "A", "Z", ESC, ":wq", CR }, gap, "abZcd\n  Z\nefZgh\n");
    h.case(ctx, target, "nvim#bi2 I skips a line short of the left edge", &.{ "l" ++ CV ++ "jj", "I", "Z", ESC, ":wq", CR }, gap, "aZbcd\n\neZfgh\n");
    h.case(ctx, target, "nvim#bi3 I keeps a line that ends exactly at the edge", &.{ "ll" ++ CV ++ "jj", "I", "Z", ESC, ":wq", CR }, "abcd\nef\nghij\n", "abZcd\nefZ\nghZij\n");
    h.case(ctx, target, "nvim#bi4 I at column 0 reaches the empty line", &.{ CV ++ "jj", "I", "Z", ESC, ":wq", CR }, "ab\n\ncd\n", "Zab\nZ\nZcd\n");
    h.case(ctx, target, "nvim#bi5 c skips a line short of the left edge", &.{ "ll" ++ CV ++ "jj", "c", "Z", ESC, ":wq", CR }, gap, "abZd\n\nefZh\n");
    h.case(ctx, target, "nvim#bi6 A over a whole block types on every row", &.{ CV ++ "jjl", "A", "XY", ESC, ":wq", CR }, "abcd\nef\nghij\n", "abXYcd\nefXY\nghXYij\n");
    // A block pasted *into* a tab breaks the tab into the spaces it was
    // drawing, so the rectangle lands on the column it was aimed at. (The
    // harness runs with tab_width 4; nvim --clean uses 8, so this one is
    // pinned to the same rule at zedit's width rather than to nvim's bytes.)
    h.case(ctx, target, "blk-tab1 a block pasted inside a tab splits it", &.{ CV ++ "jly", "jjl", "P", ":wq", CR }, "11\n22\nabcd\n\tZ\n", "11\n22\na11bcd\n 22   Z\n");
    h.case(ctx, target, "blk-tab2 a paste at the tab's own boundary leaves it", &.{ CV ++ "jly", "jj0", "P", ":wq", CR }, "11\n22\nabcd\n\tZ\n", "11\n22\n11abcd\n22\tZ\n");

    // --- sentences: the `(`/`)` motions and the `is`/`as` objects.
    const sents = "One. Two. Three.\n";
    h.case(ctx, target, "nvim#sn1 das takes the sentence and its trailing space", &.{ "fT", "das", ":wq", CR }, sents, "One. Three.\n");
    h.case(ctx, target, "nvim#sn2 dis leaves the whitespace", &.{ "fT", "dis", ":wq", CR }, sents, "One.  Three.\n");
    h.case(ctx, target, "nvim#sn3 das on the first", &.{ "das", ":wq", CR }, sents, "Two. Three.\n");
    h.case(ctx, target, "nvim#sn4 das on the last takes the leading space instead", &.{ "$", "das", ":wq", CR }, sents, "One. Two.\n");
    h.case(ctx, target, "nvim#sn5 cis replaces the sentence", &.{ "fT", "cis", "X", ESC, ":wq", CR }, sents, "One. X Three.\n");
    h.case(ctx, target, "nvim#sn6 ) moves to the next sentence", &.{ ")", "i@", ESC, ":wq", CR }, sents, "One. @Two. Three.\n");
    h.case(ctx, target, "nvim#sn7 2) counts", &.{ "2)", "i@", ESC, ":wq", CR }, sents, "One. Two. @Three.\n");
    h.case(ctx, target, "nvim#sn8 ( moves back to the sentence start", &.{ "$", "(", "i@", ESC, ":wq", CR }, sents, "One. Two. @Three.\n");
    h.case(ctx, target, "nvim#sn9 d) deletes to the next sentence", &.{ "d)", ":wq", CR }, sents, "Two. Three.\n");
    h.case(ctx, target, "nvim#sn10 a sentence does not run past its line", &.{ "fT", "das", ":wq", CR }, "One. Two.\nThree. Four.\n", "One.\nThree. Four.\n");
    h.case(ctx, target, "nvim#sn11 ! and ? end one too", &.{ "fB", "das", ":wq", CR }, "Hi! Bye? End.\n", "Hi! End.\n");

    // --- `[count].` replaces every count the change had, including one typed
    //     after the operator. The recorded keys carry no digits at all now.
    const words = "a b c d e f g h i j k l m\n";
    h.case(ctx, target, "nvim#dc1 d2w then 3. deletes three words, not six", &.{ "d2w", "3.", ":wq", CR }, words, "f g h i j k l m\n");
    h.case(ctx, target, "nvim#dc2 2d2w then 3. replaces the product", &.{ "2d2w", "3.", ":wq", CR }, words, "h i j k l m\n");
    h.case(ctx, target, "nvim#dc3 d2w then a bare . keeps the two", &.{ "d2w", ".", ":wq", CR }, words, "e f g h i j k l m\n");
    h.case(ctx, target, "nvim#dc4 dw then 3. takes a count the change never had", &.{ "dw", "3.", ":wq", CR }, words, "e f g h i j k l m\n");
    h.case(ctx, target, "nvim#dc5 a register prefix keeps the count after it", &.{ "\"a2dd", "3.", ":wq", CR }, "1\n2\n3\n4\n5\n6\n7\n8\n9\n", "6\n7\n8\n9\n");

    // `[count]` before a blockwise `A`/`I`: every caret types the text that
    // many times, exactly as the plain `3a` family does.
    const blk = "abcd\nefgh\nijkl\n";
    h.case(ctx, target, "nvim#bc1 3A types on every row", &.{ CV ++ "jj", "3A", "X", ESC, ":wq", CR }, blk, "aXXXbcd\neXXXfgh\niXXXjkl\n");
    h.case(ctx, target, "nvim#bc2 3I types on every row", &.{ CV ++ "jj", "3I", "X", ESC, ":wq", CR }, blk, "XXXabcd\nXXXefgh\nXXXijkl\n");
    h.case(ctx, target, "nvim#bc3 the whole typed text repeats", &.{ CV ++ "jj", "2A", "xy", ESC, ":wq", CR }, blk, "axyxybcd\nexyxyfgh\nixyxyjkl\n");
    h.case(ctx, target, "nvim#bc4 a wider block still appends at its right edge", &.{ CV ++ "jjl", "3A", "X", ESC, ":wq", CR }, blk, "abXXXcd\nefXXXgh\nijXXXkl\n");
    h.case(ctx, target, "nvim#bc5 3I still skips a line short of the edge", &.{ "ll" ++ CV ++ "jj", "3I", "Z", ESC, ":wq", CR }, "abcd\nef\nghij\n", "abZZZcd\nefZZZ\nghZZZij\n");
    h.case(ctx, target, "nvim#bc6 3A still pads a line short of the edge", &.{ "l" ++ CV ++ "jj", "3A", "Z", ESC, ":wq", CR }, "abcd\n\nefgh\n", "abZZZcd\n  ZZZ\nefZZZgh\n");
    h.case(ctx, target, "nvim#bc7 $3A appends at each line's own end", &.{ CV ++ "jj$", "3A", "Z", ESC, ":wq", CR }, "abcd\nef\nghij\n", "abcdZZZ\nefZZZ\nghijZZZ\n");
    h.case(ctx, target, "nvim#bc8 a count does not reach blockwise c", &.{ CV ++ "jj", "3c", "X", ESC, ":wq", CR }, blk, "Xbcd\nXfgh\nXjkl\n");
    h.case(ctx, target, "nvim#bc9 u undoes the whole counted insert", &.{ CV ++ "jj", "3A", "X", ESC, "u", ":wq", CR }, blk, blk);
    h.case(ctx, target, "nvim#bi7 u undoes the padding with the insert", &.{ "l" ++ CV ++ "jj", "A", "Z", ESC, "u", ":wq", CR }, gap, gap);
    // `$`: the block follows each line's own end, so `A` appends there and
    // pads nothing — while `I` still works off the left edge.
    h.case(ctx, target, "nvim#bi8 $A appends at each line's own end", &.{ CV ++ "jj$", "A", "Z", ESC, ":wq", CR }, ragged, "abcdZ\nefZ\nghijklZ\n");
    h.case(ctx, target, "nvim#bi9 $ survives j as the block grows", &.{ CV ++ "$jj", "A", "Z", ESC, ":wq", CR }, ragged, "abcdZ\nefZ\nghijklZ\n");
    h.case(ctx, target, "nvim#bi10 h after $ pins the right edge again", &.{ CV ++ "jj$", "h", "A", "Z", ESC, ":wq", CR }, ragged, "abcd  Z\nef    Z\nghijklZ\n");
    h.case(ctx, target, "nvim#bi11 $I still inserts at the left edge", &.{ "l" ++ CV ++ "jj$", "I", "Z", ESC, ":wq", CR }, ragged, "aZbcd\neZf\ngZhijkl\n");
    h.case(ctx, target, "nvim#bi12 $c changes to each line's end", &.{ "l" ++ CV ++ "jj$", "c", "Z", ESC, ":wq", CR }, ragged, "aZ\neZ\ngZ\n");
    h.case(ctx, target, "nvim#bi13 $A reaches an empty line at column 0", &.{ CV ++ "jj$", "A", "Z", ESC, ":wq", CR }, gap, "abcdZ\nZ\nefghZ\n");
    // Where the cursor is left afterwards, which is what makes `.` repeat the
    // same rectangle rather than one shifted right by its own width.
    h.case(ctx, target, "nvim#bi14 A ends on the block's top-left corner", &.{ CV ++ "jjl", "A", "Z", ESC, "x", ":wq", CR }, "abcd\nefgh\nijkl\n", "bZcd\nefZgh\nijZkl\n");
    h.case(ctx, target, "nvim#bi15 I ends there as well", &.{ "l" ++ CV ++ "jj", "I", "Z", ESC, "x", ":wq", CR }, "abcd\nefgh\nijkl\n", "abcd\neZfgh\niZjkl\n");
    // The append column is one past the block's right edge, and that edge is
    // the last cell of the character under the endpoint — so an endpoint on a
    // wide character or a tab puts the text past the whole of it.
    h.case(ctx, target, "nvim#bi16 A past a wide char at the edge", &.{ "l" ++ CV ++ "j", "A", "Z", ESC, ":wq", CR }, "a漢b\nc漢d\n", "a漢Zb\nc漢Zd\n");
    h.case(ctx, target, "nvim#bi17 A past a tab at the edge", &.{ "ll" ++ CV ++ "j", "A", "Q", ESC, ":wq", CR }, "abcd\n\tZ\n", "abcdQ\n\tQZ\n");
}

/// Dot-repeat and macro edge cases, all pinned to headless nvim: the count
/// rules, inserts broken by a cursor movement, blockwise changes, pasting
/// every register kind, and the ways a macro nests, repeats and aborts.
fn dotAndMacros(ctx: *h.Ctx) void {
    const nine = "1\n2\n3\n4\n5\n6\n7\n8\n9\n";
    const two_lines = "foo\nbar\n";
    // Counts: `.` alone re-uses the recorded one, and a fresh count *replaces*
    // it rather than multiplying the repeat.
    // --- 'startofline' is off in nvim: the column survives a linewise jump
    //     or a linewise delete, rather than snapping to the first non-blank.
    const four = "abcdefghijkl\nsecond line here\nthird line xx\nfourth\n";
    const MARK = "i@";
    h.case(ctx, target, "nvim#sol1 G keeps the column", &.{ "2G", "9l", "G", MARK, ESC, ":wq", CR }, four, "abcdefghijkl\nsecond line here\nthird line xx\nfourt@h\n");
    h.case(ctx, target, "nvim#sol2 gg keeps the column", &.{ "3G", "9l", "gg", MARK, ESC, ":wq", CR }, four, "abcdefghi@jkl\nsecond line here\nthird line xx\nfourth\n");
    h.case(ctx, target, "nvim#sol3 {n}G keeps the column", &.{ "9l", "3G", MARK, ESC, ":wq", CR }, four, "abcdefghijkl\nsecond line here\nthird lin@e xx\nfourth\n");
    h.case(ctx, target, "nvim#sol4 H keeps the column", &.{ "3G", "9l", "H", MARK, ESC, ":wq", CR }, four, "abcdefghi@jkl\nsecond line here\nthird line xx\nfourth\n");
    h.case(ctx, target, "nvim#sol5 L keeps the column", &.{ "9l", "L", MARK, ESC, ":wq", CR }, four, "abcdefghijkl\nsecond line here\nthird line xx\nfourt@h\n");
    h.case(ctx, target, "nvim#sol6 dd keeps the column", &.{ "9l", "dd", MARK, ESC, ":wq", CR }, four, "second li@ne here\nthird line xx\nfourth\n");
    h.case(ctx, target, "nvim#sol7 dj keeps the column", &.{ "9l", "dj", MARK, ESC, ":wq", CR }, four, "third lin@e xx\nfourth\n");
    h.case(ctx, target, "nvim#sol8 Vd keeps the column", &.{ "9l", "V", "d", MARK, ESC, ":wq", CR }, four, "second li@ne here\nthird line xx\nfourth\n");
    h.case(ctx, target, "nvim#sol9 the column clamps to a shorter line", &.{ "9l", "V", "d", MARK, ESC, ":wq", CR }, "abcdefghijkl\nab\ncd\n", "a@b\ncd\n");
    // A linewise visual yank goes to column 0 unless the cursor was already
    // the top end of the selection.
    h.case(ctx, target, "nvim#sol10 Vy goes to column 0", &.{ "9l", "V", "y", MARK, ESC, ":wq", CR }, four, "@abcdefghijkl\nsecond line here\nthird line xx\nfourth\n");
    h.case(ctx, target, "nvim#sol11 Vky keeps the column", &.{ "2G", "9l", "V", "k", "y", MARK, ESC, ":wq", CR }, four, "abcdefghi@jkl\nsecond line here\nthird line xx\nfourth\n");
    h.case(ctx, target, "nvim#sol12 yy keeps the column", &.{ "9l", "yy", MARK, ESC, ":wq", CR }, four, "abcdefghi@jkl\nsecond line here\nthird line xx\nfourth\n");

    // --- counts inside visual mode: digits were falling through to the
    //     motion dispatch, so every count moved one.
    h.case(ctx, target, "nvim#vc1 v3h", &.{ "9l", "v", "3h", "d", ":wq", CR }, four, "abcdefkl\nsecond line here\nthird line xx\nfourth\n");
    h.case(ctx, target, "nvim#vc2 v3l", &.{ "2l", "v", "3l", "d", ":wq", CR }, four, "abghijkl\nsecond line here\nthird line xx\nfourth\n");
    h.case(ctx, target, "nvim#vc3 v2j", &.{ "v", "2j", "d", ":wq", CR }, four, "hird line xx\nfourth\n");
    h.case(ctx, target, "nvim#vc4 v3w", &.{ "v", "3w", "d", ":wq", CR }, "aa bb cc dd ee ff\n", "d ee ff\n");
    h.case(ctx, target, "nvim#vc5 v3G is a line number, not a repeat", &.{ "v", "3G", "d", ":wq", CR }, four, "hird line xx\nfourth\n");
    h.case(ctx, target, "nvim#vc6 a bare 0 in visual is still a motion", &.{ "5l", "v", "0", "d", ":wq", CR }, four, "ghijkl\nsecond line here\nthird line xx\nfourth\n");

    // --- [count] before an insert command types the text that many times.
    h.case(ctx, target, "nvim#ic1 3a", &.{ "3a", "X", ESC, ":wq", CR }, "abc\n", "aXXXbc\n");
    h.case(ctx, target, "nvim#ic2 3i", &.{ "3i", "X", ESC, ":wq", CR }, "abc\n", "XXXabc\n");
    h.case(ctx, target, "nvim#ic3 3A", &.{ "3A", "X", ESC, ":wq", CR }, "abc\n", "abcXXX\n");
    h.case(ctx, target, "nvim#ic4 3I", &.{ "3I", "X", ESC, ":wq", CR }, "  abc\n", "  XXXabc\n");
    h.case(ctx, target, "nvim#ic5 3o brings its own lines", &.{ "3o", "X", ESC, ":wq", CR }, "abc\n", "abc\nX\nX\nX\n");
    h.case(ctx, target, "nvim#ic6 3O brings its own lines", &.{ "3O", "X", ESC, ":wq", CR }, "abc\n", "X\nX\nX\nabc\n");
    h.case(ctx, target, "nvim#ic7 the whole typed text repeats", &.{ "2a", "xy", ESC, ":wq", CR }, "abc\n", "axyxybc\n");
    h.case(ctx, target, "nvim#ic8 a newline typed inside it repeats too", &.{ "3a", "X\rY", ESC, ":wq", CR }, "abc\n", "aX\nYX\nYX\nYbc\n");
    h.case(ctx, target, "nvim#ic9 . repeats the counted insert whole", &.{ "3a", "X", ESC, ".", ":wq", CR }, "abc\n", "aXXXXXXbc\n");
    h.case(ctx, target, "nvim#ic10 3s still substitutes three and inserts once", &.{ "3s", "X", ESC, ":wq", CR }, "abcdef\n", "Xdef\n");

    // --- visual p/P replaces the selection, and what it replaced becomes the
    //     unnamed register.
    const abcd = "aaa\nbbb\nccc\nddd\n";
    h.case(ctx, target, "nvim#vp1 charwise register into a charwise selection", &.{ "ylj", "v", "l", "p", ":wq", CR }, abcd, "aaa\nab\nccc\nddd\n");
    h.case(ctx, target, "nvim#vp2 linewise register into a charwise selection splits the line", &.{ "yy", "j", "v", "l", "p", ":wq", CR }, abcd, "aaa\n\naaa\nb\nccc\nddd\n");
    h.case(ctx, target, "nvim#vp3 charwise register into a linewise selection", &.{ "yl", "j", "V", "p", ":wq", CR }, abcd, "aaa\na\nccc\nddd\n");
    h.case(ctx, target, "nvim#vp4 linewise register into a linewise selection", &.{ "yy", "j", "V", "p", ":wq", CR }, abcd, "aaa\naaa\nccc\nddd\n");
    h.case(ctx, target, "nvim#vp5 a two-line selection", &.{ "yy", "j", "V", "j", "p", ":wq", CR }, abcd, "aaa\naaa\nddd\n");
    h.case(ctx, target, "nvim#vp6 what was replaced becomes the unnamed register", &.{ "yy", "j", "V", "p", "j", "p", ":wq", CR }, abcd, "aaa\naaa\nccc\nbbb\nddd\n");
    h.case(ctx, target, "nvim#vp7 visual P is visual p", &.{ "yy", "j", "V", "P", ":wq", CR }, abcd, "aaa\naaa\nccc\nddd\n");
    h.case(ctx, target, "nvim#vp8 the cursor lands on the pasted text", &.{ "yy", "j", "V", "p", MARK, ESC, ":wq", CR }, abcd, "aaa\n@aaa\nccc\nddd\n");

    // --- a bare `/` or `?` repeats the last pattern in the new direction.
    const xs = "one X two\nthree X four\nfive X six\n";
    h.case(ctx, target, "nvim#bs1 bare / repeats", &.{ "/X", CR, "/", CR, "x", ":wq", CR }, xs, "one X two\nthree  four\nfive X six\n");
    h.case(ctx, target, "nvim#bs2 bare / twice walks on", &.{ "/X", CR, "/", CR, "/", CR, "x", ":wq", CR }, xs, "one X two\nthree X four\nfive  six\n");
    h.case(ctx, target, "nvim#bs3 bare ? repeats backwards", &.{ "G", "?X", CR, "?", CR, "x", ":wq", CR }, xs, "one  two\nthree X four\nfive X six\n");
    h.case(ctx, target, "nvim#bs4 with no pattern yet it does nothing", &.{ "/", CR, "x", ":wq", CR }, xs, "ne X two\nthree X four\nfive X six\n");

    // Visual mode has no `dd`: `d` deletes the selection and returns to
    // normal, so a second `d` arms a *new* operator and the next motion
    // completes it. Reported as "d then j deletes more lines"; it is what nvim
    // does, verified against it, and worth pinning because it is surprising.
    const ten = "line1\nline2\nline3\nline4\nline5\nline6\nline7\nline8\nline9\nline10\n";
    h.case(ctx, target, "nvim#vd1 v then an aborted object, k, d is charwise", &.{ "5G", "v", "i", "k", "k", "d", "j", ":wq", CR }, ten, "line1\nline2\nline3\nine5\nline6\nline7\nline8\nline9\nline10\n");
    h.case(ctx, target, "nvim#vd2 a second d after a visual d arms an operator, and j completes it", &.{ "5G", "v", "i", "k", "k", "d", "d", "j", ":wq", CR }, ten, "line1\nline2\nline3\nline7\nline8\nline9\nline10\n");
    h.case(ctx, target, "nvim#vd3 the same without the object key", &.{ "5G", "v", "k", "k", "d", "j", ":wq", CR }, ten, "line1\nline2\nine5\nline6\nline7\nline8\nline9\nline10\n");
    h.case(ctx, target, "nvim#dm1 3dd then . deletes three more", &.{ "3dd", ".", ":wq", CR }, nine, "7\n8\n9\n");
    h.case(ctx, target, "nvim#dm2 3dd then 2. deletes only two", &.{ "3dd", "2.", ":wq", CR }, nine, "6\n7\n8\n9\n");
    h.case(ctx, target, "nvim#dm3 3x then 2. removes five characters, not nine", &.{ "3x", "2.", ":wq", CR }, "abcdefghij\n", "fghij\n");
    h.case(ctx, target, "nvim#dm4 2dw then 3. replaces the count", &.{ "2dw", "3.", ":wq", CR }, "a b c d e f g h i\n", "f g h i\n");
    h.case(ctx, target, "nvim#dm5 2dw then a bare . keeps it", &.{ "2dw", ".", ":wq", CR }, "a b c d e f g\n", "e f g\n");
    h.case(ctx, target, "nvim#dm6 2dd then 4. replaces a doubled operator's count", &.{ "2dd", "4.", ":wq", CR }, nine, "7\n8\n9\n");
    h.case(ctx, target, "nvim#dm7 a leading 0 is the motion, not a count", &.{ "x", "0.", ":wq", CR }, "abcdef\n", "cdef\n");
    // The substituted count belongs *after* a `"{reg}` prefix, which vim keeps.
    // In front of it the two digit runs fuse: `3.` after `"a2dd` became `32dd`
    // and took the whole file.
    h.case(ctx, target, "nvim#dm8a 3. after \"a2dd replaces only the count", &.{ "\"a2dd", "3.", ":wq", CR }, nine, "6\n7\n8\n9\n");
    h.case(ctx, target, "nvim#dm8b 2. after \"a3x likewise", &.{ "\"a3x", "2.", ":wq", CR }, "abcdefghij\n", "fghij\n");
    // The count rule matters most for an operator whose motion is a *click*:
    // the replayed screen cell is re-resolved against a cursor the previous
    // replay already moved, so repeating the change N times used to drift.
    const grid = "abcdefgh\nijklmnop\nqrstuvwx\nyz012345\n67890abc\ndefghijk\n";
    h.case(ctx, target, "nvim#dm8 2. after d + click", &.{ "ll", "d", click(3, 2), "2.", ":wq", CR }, grid, "ab890abc\ndefghijk\n");
    h.case(ctx, target, "nvim#dm9 a bare . after d + click", &.{ "ll", "d", click(3, 2), ".", ":wq", CR }, grid, "ab890abc\ndefghijk\n");
    // `.` is not itself a change, so repeating it repeats the change again
    // rather than repeating the repeat.
    h.case(ctx, target, "nvim#dm10 dw then two dots", &.{ "dw", "..", ":wq", CR }, "a b c d e\n", "d e\n");
    h.case(ctx, target, "nvim#dm11 x then three dots", &.{ "x", "...", ":wq", CR }, "abcdef\n", "ef\n");
    // A cursor movement mid-insert splits the change: vim repeats only the
    // text typed after it, and as a plain `i` whatever opened the insert.
    h.case(ctx, target, "nvim#dm12 . after an insert broken by Left", &.{ "i", "AB\x1b[DC", ESC, "j0", ".", ":wq", CR }, two_lines, "ACBfoo\nCbar\n");
    h.case(ctx, target, "nvim#dm13 . after an A broken by Left inserts, not appends", &.{ "A", "XY\x1b[DZ", ESC, "j0", ".", ":wq", CR }, two_lines, "fooXZY\nZbar\n");
    h.case(ctx, target, "nvim#dm14 . after an insert broken by Right", &.{ "i", "AB\x1b[CC", ESC, "j0", ".", ":wq", CR }, "foobar\nbazqux\n", "ABfCoobar\nCbazqux\n");
    h.case(ctx, target, "nvim#dm15 backspace does not break the insert", &.{ "i", "AB\x7fC", ESC, "j0", ".", ":wq", CR }, two_lines, "ACfoo\nACbar\n");
    // Operator + text-object changes.
    h.case(ctx, target, "nvim#dm16 . after ciw", &.{ "ciw", "X", ESC, "j0", ".", ":wq", CR }, "one two\nthree four\n", "X two\nX four\n");
    h.case(ctx, target, "nvim#dm17 . after ct,", &.{ "ct,", "X", ESC, "j0", ".", ":wq", CR }, "aaa,bbb\nccc,ddd\n", "X,bbb\nX,ddd\n");
    // Blockwise inserts and changes repeat as the same rectangle.
    h.case(ctx, target, "nvim#dm18 . after a blockwise A", &.{ CV ++ "jjl", "A", "Z", ESC, "3j", ".", ":wq", CR }, "abcd\nef\nghij\nklmn\nop\nqrst\n", "abZcd\nefZ\nghZij\nklZmn\nopZ\nqrZst\n");
    h.case(ctx, target, "nvim#dm19 . after a blockwise A that padded", &.{ "l" ++ CV ++ "jj", "A", "Z", ESC, "3j", ".", ":wq", CR }, "abcd\n\nefgh\nijkl\n\nmnop\n", "abZcd\n  Z\nefZgh\nijZkl\n  Z\nmnZop\n");
    h.case(ctx, target, "nvim#dm20 . after a blockwise I", &.{ CV ++ "jj", "I", "Z", ESC, "3j", ".", ":wq", CR }, "aaaa\nbbbb\ncccc\ndddd\neeee\nffff\n", "Zaaaa\nZbbbb\nZcccc\nZdddd\nZeeee\nZffff\n");
    h.case(ctx, target, "nvim#dm21 . after a blockwise c", &.{ "l" ++ CV ++ "jj", "c", "Z", ESC, "3j", ".", ":wq", CR }, "abcd\nefgh\nijkl\nmnop\nqrst\nuvwx\n", "aZcd\neZgh\niZkl\nmZop\nqZst\nuZwx\n");
    // `.` after a paste, once per register kind.
    h.case(ctx, target, "nvim#dm22 . after a charwise p", &.{ "ylj0", "p", ".", ":wq", CR }, "ab\ncd\n", "ab\ncaad\n");
    h.case(ctx, target, "nvim#dm23 . after a linewise p", &.{ "yy", "j", "p", ".", ":wq", CR }, "ab\ncd\n", "ab\ncd\nab\nab\n");
    h.case(ctx, target, "nvim#dm24 . after a blockwise p", &.{ CV ++ "jly", "jj0", "p", ".", ":wq", CR }, "11\n22\nabcd\nefgh\n", "11\n22\na1111bcd\ne2222fgh\n");
    h.case(ctx, target, "nvim#dm25 . after a blockwise P", &.{ CV ++ "jly", "jjl", "P", ".", ":wq", CR }, "11\n22\nabcd\nefgh\n", "11\n22\na1111bcd\ne2222fgh\n");
    // Macros: recording runs the keys as they are typed, and a replay is a
    // second run of the same bytes — including a `.` and a nested `@`.
    h.case(ctx, target, "nvim#dm26 a macro that records a dot", &.{ "dw", "qq", "j0.", "q", "@q", ":wq", CR }, "a b c\nd e f\ng h i\n", "b c\ne f\nh i\n");
    h.case(ctx, target, "nvim#dm27 a macro that records a count", &.{ "qa", "2dd", "q", "@a", ":wq", CR }, nine, "5\n6\n7\n8\n9\n");
    h.case(ctx, target, "nvim#dm28 a macro replaying a macro", &.{ "qadd", "q", "qb@a@a", "q", "@b", ":wq", CR }, "1\n2\n3\n4\n5\n6\n7\n8\n", "6\n7\n8\n");
    h.case(ctx, target, "nvim#dm29 a counted replay", &.{ "qadd", "q", "3@a", ":wq", CR }, "1\n2\n3\n4\n5\n6\n7\n8\n", "5\n6\n7\n8\n");
    h.case(ctx, target, "nvim#dm30 @@ repeats the last macro", &.{ "qadd", "q", "@a", "@@", ":wq", CR }, "1\n2\n3\n4\n5\n6\n", "4\n5\n6\n");
    h.case(ctx, target, "nvim#dm31 @@ takes a count", &.{ "qadd", "q", "@a", "2@@", ":wq", CR }, "1\n2\n3\n4\n5\n6\n7\n8\n", "5\n6\n7\n8\n");
    h.case(ctx, target, "nvim#dm32 q re-records over an existing register", &.{ "qax", "q", "qaxx", "q", "@a", ":wq", CR }, "abcdef\n", "f\n");
    h.case(ctx, target, "nvim#dm33 a macro records a blockwise paste", &.{ CV ++ "jly", "qq", "jj0p", "q", "G", "k", "@q", ":wq", CR }, "11\n22\nabcd\nefgh\nijkl\nmnop\n", "11\n22\na11bcd\ne22fgh\nijkl\nmnop\n");
    // An error stops the replay where it happened — the keys after it never
    // run, and neither do the repetitions left on a count.
    h.case(ctx, target, "nvim#dm34 a replay stops at a motion that cannot move", &.{ "qq", "jx", "q", "G", "@q", ":wq", CR }, "aaa\nbbb\nccc\n", "aaa\nbb\nccc\n");
    h.case(ctx, target, "nvim#dm35 …and at a find with no match", &.{ "qq", "fzx", "q", "gg", "@q", ":wq", CR }, "axb\nayb\n", "xb\nayb\n");
    h.case(ctx, target, "nvim#dm36 …and at a search with no match", &.{ "qq", "x/zzz\rx", "q", "gg", "@q", ":wq", CR }, "a\nb\nc\n", "\nb\nc\n");
    h.case(ctx, target, "nvim#dm37 a counted replay stops at the error too", &.{ "qq", "IX" ++ ESC ++ "j", "q", "gg", "3@q", ":wq", CR }, "aaa\nbbb\nccc\n", "XXaaa\nXbbb\nXccc\n");
    // The abort is scoped to the replay: the next key a person types runs.
    h.case(ctx, target, "nvim#dm38 a failed replay does not swallow the next key", &.{ "qq", "/zzz\r", "q", "@q", "x", ":wq", CR }, "abc\n", "bc\n");
}
