//! Vim-compatibility suite: each case's expected result was generated by
//! driving real Neovim headlessly (NVIM v0.12.4, `--headless -u NONE -i NONE
//! --noplugin`), so these assert byte-for-byte agreement with vim semantics —
//! including the classic traps: `cw` acts like `ce`; `dw` eats trailing
//! spaces but never crosses a newline; `di(`/`ci'` seek forward on the line
//! when the cursor is before the pair; deleting every line writes a 0-byte
//! file; `daw` + `P` round-trips; `J` leaves the cursor on the joining space.

const std = @import("std");
const h = @import("../harness.zig");

const ESC = "\x1b";
const CR = "\r";
const target = "/tmp/zedit_it_compat.txt";

pub fn run(ctx: *h.Ctx) !void {
    h.case(ctx, target, "nvim#1 dw deletes word + trailing space", &.{ "dw", ":wq", CR }, "foo bar baz\n", "bar baz\n");
    h.case(ctx, target, "nvim#2 cw acts like ce (space survives)", &.{ "cw", "X", ESC, ":wq", CR }, "foo bar\n", "X bar\n");
    h.case(ctx, target, "nvim#3 dw on last word stops at newline", &.{ "wdw", ":wq", CR }, "foo  bar\n", "foo  \n");
    h.case(ctx, target, "nvim#4 dw from mid-word", &.{ "ldw", ":wq", CR }, "foo bar\n", "fbar\n");
    h.case(ctx, target, "nvim#5 dw sole word + dot repeat", &.{ "dwj.", ":wq", CR }, "foo\nbar\n", "\n\n");
    h.case(ctx, target, "nvim#6 d$ empties the line, keeps it", &.{ "d$", ":wq", CR }, "abc def\n", "\n");
    h.case(ctx, target, "nvim#7 2dw", &.{ "2dw", ":wq", CR }, "one two three\n", "three\n");
    h.case(ctx, target, "nvim#8 x then $p pastes after EOL char", &.{ "x$p", ":wq", CR }, "hello\n", "elloh\n");
    h.case(ctx, target, "nvim#9 di( seeks forward to the pair", &.{ "di(", ":wq", CR }, "a(b c)d\n", "a()d\n");
    h.case(ctx, target, "nvim#10 ci( seeks forward", &.{ "ci(", "Z", ESC, ":wq", CR }, "x (abc) y\n", "x (Z) y\n");
    h.case(ctx, target, "nvim#11 ci' seeks forward", &.{ "ci'", "Q", ESC, ":wq", CR }, "foo 'bar' baz\n", "foo 'Q' baz\n");
    h.case(ctx, target, "nvim#12 yy j p linewise paste below", &.{ "yyjp", ":wq", CR }, "aaa\nbbb\nccc\n", "aaa\nbbb\naaa\nccc\n");
    h.case(ctx, target, "nvim#13 J leaves cursor on joining space", &.{ "Jx", ":wq", CR }, "abc\ndef\n", "abcdef\n");
    h.case(ctx, target, "nvim#14 I inserts at first non-blank", &.{ "I", ">", ESC, ":wq", CR }, "  indented\n", "  >indented\n");
    h.case(ctx, target, "nvim#15 ~ toggles case", &.{ "~", ":wq", CR }, "word\n", "Word\n");
    h.case(ctx, target, "nvim#16 delete-all writes 0 bytes", &.{ "ggVGd", ":wq", CR }, "one\ntwo\nthree\n", "");
    h.case(ctx, target, "nvim#17 * jumps to next occurrence", &.{ "*x", ":wq", CR }, "foo bar foo\n", "foo bar oo\n");
    h.case(ctx, target, "nvim#18 3x clamps at EOL", &.{ "3x", ":wq", CR }, "abc\n", "\n");
    h.case(ctx, target, "nvim#19 df<space>", &.{ "df ", ":wq", CR }, "a b c d\n", "b c d\n");
    h.case(ctx, target, "nvim#20 f( then ci( from the paren", &.{ "f(ci(", "X", ESC, ":wq", CR }, "foo(bar)\n", "foo(X)\n");
    h.case(ctx, target, "nvim#21 daw + P round-trips", &.{ "dawP", ":wq", CR }, "one two\n", "one two\n");
    h.case(ctx, target, "nvim#22 visual U uppercases selection", &.{ "veU", ":wq", CR }, "hello world\n", "HELLO world\n");
    h.case(ctx, target, "nvim#23 dw then dot at new position", &.{ "dw.", ":wq", CR }, "abc def ghi\n", "ghi\n");
    h.case(ctx, target, "nvim#24 ddp swaps lines", &.{ "ddp", ":wq", CR }, "x\ny\nz\n", "y\nx\nz\n");
    h.case(ctx, target, "nvim#25 w then cw on second word", &.{ "wcw", "ZZZ", ESC, ":wq", CR }, "aaa bbb\n", "aaa ZZZ\n");

    // :s substitution — expected results generated by the same headless nvim
    // (patterns chosen to mean the same thing in vim magic and zedit's modern
    // regex syntax).
    h.case(ctx, target, "nvim#s1 :%s g flag replaces all", &.{ ":%s/foo/bar/g\r", ":wq", CR }, "foo foo\nxfoo\n", "bar bar\nxbar\n");
    h.case(ctx, target, "nvim#s2 :s current line, first only", &.{ ":s/o/0/\r", ":wq", CR }, "foo\nfoo\n", "f0o\nfoo\n");
    h.case(ctx, target, "nvim#s3 :2,3s range", &.{ ":2,3s/a/X/g\r", ":wq", CR }, "aa\naa\naa\naa\n", "aa\nXX\nXX\naa\n");
    h.case(ctx, target, "nvim#s4 dot metachar", &.{ ":%s/b.d/X/g\r", ":wq", CR }, "bad bed\nbid\n", "X X\nX\n");
    h.case(ctx, target, "nvim#s5 anchor ^ prefixes lines", &.{ ":%s/^/> /\r", ":wq", CR }, "a\nb\n", "> a\n> b\n");
    h.case(ctx, target, "nvim#s6 i flag ignores case", &.{ ":%s/FOO/x/gi\r", ":wq", CR }, "FOO foo\n", "x x\n");
    h.case(ctx, target, "nvim#s7 character classes", &.{ ":%s/[0-9][0-9]*/N/g\r", ":wq", CR }, "a1 b22 c333\n", "aN bN cN\n");
    h.case(ctx, target, "nvim#s8 no match leaves file unchanged", &.{ ":%s/xyz/Q/g\r", ":wq", CR }, "no match here\n", "no match here\n");

    // Jumplist (Ctrl-o = \x0f back, Ctrl-i = Tab forward) — nvim-verified.
    h.case(ctx, target, "nvim#j1 G then Ctrl-o returns", &.{ "G\x0fx", ":wq", CR }, "aaa\nbbb\nccc\nddd\neee\n", "aa\nbbb\nccc\nddd\neee\n");
    h.case(ctx, target, "nvim#j2 search then Ctrl-o returns to origin", &.{ "/ddd\r\x0fx", ":wq", CR }, "aaa\nbbb\nccc\nddd\neee\n", "aa\nbbb\nccc\nddd\neee\n");
    h.case(ctx, target, "nvim#j3 Ctrl-o then Ctrl-i goes forward again", &.{ "G\x0f\tx", ":wq", CR }, "aaa\nbbb\nccc\nddd\neee\n", "aaa\nbbb\nccc\nddd\nee\n");

    // Autoindent (nvim has 'autoindent' on by default; ours matches).
    h.case(ctx, target, "nvim#a1 o inherits indent", &.{ "obar", ESC, ":wq", CR }, "    foo\n", "    foo\n    bar\n");
    h.case(ctx, target, "nvim#a2 O inherits indent", &.{ "Obar", ESC, ":wq", CR }, "    foo\n", "    bar\n    foo\n");
    h.case(ctx, target, "nvim#a3 Enter inherits indent", &.{ "A\rbar", ESC, ":wq", CR }, "    foo\n", "    foo\n    bar\n");
    h.case(ctx, target, "nvim#a4 blank o-line is stripped on Esc", &.{ "o", ESC, ":wq", CR }, "    foo\n", "    foo\n\n");
    h.case(ctx, target, "nvim#a5 blank intermediate stripped, indent carries", &.{ "A\r\rbar", ESC, ":wq", CR }, "    foo\n", "    foo\n\n    bar\n");
    h.case(ctx, target, "nvim#a6 Enter mid-line moves tail with indent", &.{ "fbi\r", ESC, ":wq", CR }, "    foo bar\n", "    foo \n    bar\n");
    h.case(ctx, target, "nvim#a7 cc keeps the indent", &.{ "ccbar", ESC, ":wq", CR }, "    foo\n", "    bar\n");
    h.case(ctx, target, "nvim#a8 tab indent copied verbatim", &.{ "obar", ESC, ":wq", CR }, "\tfoo\n", "\tfoo\n\tbar\n");
    h.case(ctx, target, "nvim#a9 blank Enter-line stripped on Esc", &.{ "A\r", ESC, ":wq", CR }, "    foo\n", "    foo\n\n");

    // Counted find-char: `[count]f/t/F/T` and `[count];`. Ground truth from
    // headless nvim on "alpha beta gamma alpha beta" — vim counts occurrences
    // and fails the motion outright when there are too few.
    const ff = "alpha beta gamma alpha beta\n";
    h.case(ctx, target, "nvim#f1 3fa lands on the third a", &.{ "3fa", "x", ":wq", CR }, ff, "alpha beta gmma alpha beta\n");
    h.case(ctx, target, "nvim#f2 2ta stops before the second a", &.{ "2ta", "x", ":wq", CR }, ff, "alpha bea gamma alpha beta\n");
    h.case(ctx, target, "nvim#f3 d3fa deletes through the third a", &.{ "d3fa", ":wq", CR }, ff, "mma alpha beta\n");
    h.case(ctx, target, "nvim#f4 2; repeats the find twice", &.{ "fa", "2;", "x", ":wq", CR }, ff, "alpha beta gmma alpha beta\n");
    h.case(ctx, target, "nvim#f5 $3Fa searches backwards by count", &.{ "$", "3Fa", "x", ":wq", CR }, ff, "alpha beta gamm alpha beta\n");
    h.case(ctx, target, "nvim#f6 a count past the last match does nothing", &.{ "9fa", "x", ":wq", CR }, ff, "lpha beta gamma alpha beta\n");

    // The undo tree: `g-`/`g+` walk states in the order they were made, so a
    // change stranded by undo-then-edit is still reachable. Ground truth from
    // headless nvim on "one" with the same keys.
    const ut = "one\n";
    h.case(ctx, target, "nvim#u1 u returns to the state before the insert", &.{ "IA", ESC, "u", ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u2 editing after an undo replaces the redo", &.{ "IA", ESC, "u", "IB", ESC, ":wq", CR }, ut, "Bone\n");
    h.case(ctx, target, "nvim#u3 g- reaches the abandoned branch", &.{ "IA", ESC, "u", "IB", ESC, "g-", ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u4 g- again reaches the original", &.{ "IA", ESC, "u", "IB", ESC, "g-", "g-", ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u5 g+ walks back forward in time", &.{ "IA", ESC, "u", "IB", ESC, "g-", "g-", "g+", ":wq", CR }, ut, "Aone\n");

    // `:earlier` / `:later`, counted in changes and in time. Ground truth from
    // real nvim driven through a pty (running the keys as `-c` arguments joins
    // the two inserts into one undo block and hides the difference).
    h.case(ctx, target, "nvim#u6 :earlier 1 steps back one change", &.{ "IA", ESC, "IB", ESC, ":earlier 1", CR, ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u7 :earlier 2 steps back two", &.{ "IA", ESC, "IB", ESC, ":earlier 2", CR, ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u8 :later 1 comes forward again", &.{ "IA", ESC, "IB", ESC, ":earlier 2", CR, ":later 1", CR, ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u9 :earlier 1h clamps to the oldest state", &.{ "IA", ESC, "IB", ESC, ":earlier 1h", CR, ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u10 :later 1h clamps to the newest", &.{ "IA", ESC, "IB", ESC, ":earlier 1h", CR, ":later 1h", CR, ":wq", CR }, ut, "BAone\n");

    // `:earlier Nf` / `:later Nf` count file writes, not changes. Ground truth
    // from real nvim through a pty: write, edit, write, edit, then walk back.
    const wr = &[_][]const u8{ "IA", ESC, ":w", CR, "IB", ESC, ":w", CR, "IC", ESC };
    h.case(ctx, target, "nvim#u11 :earlier 1f returns to the last write", wr ++ &[_][]const u8{ ":earlier 1f", CR, ":wq", CR }, ut, "BAone\n");
    h.case(ctx, target, "nvim#u12 :earlier 2f goes back two writes", wr ++ &[_][]const u8{ ":earlier 2f", CR, ":wq", CR }, ut, "Aone\n");
    h.case(ctx, target, "nvim#u13 :earlier 3f clamps past the first write", wr ++ &[_][]const u8{ ":earlier 3f", CR, ":wq", CR }, ut, "one\n");
    h.case(ctx, target, "nvim#u14 :later 1f comes forward a write", wr ++ &[_][]const u8{ ":earlier 2f", CR, ":later 1f", CR, ":wq", CR }, ut, "BAone\n");
    h.case(ctx, target, "nvim#u15 :earlier 1f with no writes goes to the start", &.{ "IA", ESC, "IB", ESC, ":earlier 1f", CR, ":wq", CR }, ut, "one\n");

    // Visual-mode "around" objects — nvim-verified on "x = add(a, b)".
    const va = "x = add(a, b)\n";
    h.case(ctx, target, "nvim#v1 va( takes the brackets", &.{ "fa", "va(d", ":wq", CR }, va, "x = add\n");
    h.case(ctx, target, "nvim#v2 vi( keeps them", &.{ "fa", "vi(d", ":wq", CR }, va, "x = add()\n");
    h.case(ctx, target, "nvim#v3 vaw takes the word and its space", &.{ "fa", "vawd", ":wq", CR }, va, "x =(a, b)\n");
    h.case(ctx, target, "nvim#v4 vaW takes the whole WORD", &.{ "fa", "vaWd", ":wq", CR }, va, "x = b)\n");

    // Command-line history (Up = \x1b[A, Down = \x1b[B) — nvim-verified.
    // ':' Up recalls the last ex command; Enter replays it.
    h.case(ctx, target, "nvim#h1 : Up replays last command", &.{ ":s/a/X/\r", "j", ":", "\x1b[A", "\r", ":wq", CR }, "aa\naa\n", "Xa\nXa\n");
    // Up filters by the typed prefix: ':s' skips the ':2' entry.
    h.case(ctx, target, "nvim#h2 Up filters by typed prefix", &.{ ":s/a/X/\r", ":2\r", ":s", "\x1b[A", "\r", ":wq", CR }, "aa\naa\naa\n", "Xa\nXa\naa\n");
    // '/' has its own history; Up recalls the last pattern.
    h.case(ctx, target, "nvim#h3 / Up recalls last search", &.{ "/alpha\r", "gg", "/", "\x1b[A", "\r", "x", ":wq", CR }, "one\nalpha\ntwo\nalpha\n", "one\nlpha\ntwo\nalpha\n");
    // Down past the newest entry restores the typed-but-unrun line.
    h.case(ctx, target, "nvim#h4 Down restores the typed line", &.{ ":s/a/X/\r", "j", ":s/a/Y/", "\x1b[A", "\x1b[B", "\r", ":wq", CR }, "aa\naa\n", "Xa\nYa\n");
    // :qa with unsaved changes refuses (nvim E37); the :wq still writes.
    h.case(ctx, target, "nvim#h5 :qa refuses unsaved changes", &.{ "x", ":qa\r", ":wq", CR }, "aa\n", "a\n");

    // Mid-line command-line editing (Left/Right/Home/End/Ctrl-b/Ctrl-e move a
    // cursor within the line; typing inserts, backspace deletes before it).
    // Every expectation generated by driving real nvim through a tmux pty and
    // reading the file it saved, e.g. e1's probe: `:s/a/XY/` Left Left Left
    // `Z` CR on "ab" left the file "ZXYb" — the Z landed before the X.
    h.case(ctx, target, "nvim#e1 Left then typing inserts before the cursor", &.{ ":s/a/XY/", "\x1b[D\x1b[D\x1b[D", "Z", "\r", ":wq", CR }, "ab\n", "ZXYb\n");
    // Probe: `:s/a/X/` Home `2` -> ":2s/a/X/" (the 2 landed at column 0).
    h.case(ctx, target, "nvim#e2 Home jumps to the start of the line", &.{ ":s/a/X/", "\x1b[H", "2", "\r", ":wq", CR }, "aa\naa\n", "aa\nXa\n");
    // Probe: `:s/aXb/Y/` Left x4 BS -> ":s/ab/Y/" (deleted the char before the cursor).
    h.case(ctx, target, "nvim#e3 backspace deletes before the cursor", &.{ ":s/aXb/Y/", "\x1b[D\x1b[D\x1b[D\x1b[D", "\x7f", "\r", ":wq", CR }, "ab\n", "Y\n");
    // Probe: `:s/a/Q/` Left Left Right `R` -> ":s/a/QR/" (Right moved right mid-line).
    h.case(ctx, target, "nvim#e4 Right moves the cursor right", &.{ ":s/a/Q/", "\x1b[D\x1b[D", "\x1b[C", "R", "\r", ":wq", CR }, "ab\n", "QRb\n");
    // Probe: `:s/a/W` Left Left End `/` -> ":s/a/W/" (End jumped to end-of-line).
    h.case(ctx, target, "nvim#e5 End jumps to the end of the line", &.{ ":s/a/W", "\x1b[D\x1b[D", "\x1b[F", "/", "\r", ":wq", CR }, "ab\n", "Wb\n");
    // Probes: Ctrl-b / Ctrl-e are vim's c_CTRL-B / c_CTRL-E (start / end).
    h.case(ctx, target, "nvim#e6 Ctrl-b to the beginning", &.{ ":s/a/X/", "\x02", "2", "\r", ":wq", CR }, "aa\naa\n", "aa\nXa\n");
    h.case(ctx, target, "nvim#e7 Ctrl-e to the end", &.{ ":s/a/W", "\x1b[D\x1b[D", "\x05", "/", "\r", ":wq", CR }, "ab\n", "Wb\n");
    // Probe: Home BS `2` -> ":2s/a/X/" — backspace at column 0 of a NON-empty
    // line is a no-op in nvim (it neither deletes nor cancels the cmdline).
    h.case(ctx, target, "nvim#e8 backspace at column 0 is a no-op", &.{ ":s/a/X/", "\x1b[H", "\x7f", "2", "\r", ":wq", CR }, "aa\naa\n", "aa\nXa\n");
    // Probe: `:` Up recalls ":s/a/X/" with the cursor at END of line, so the
    // typed `g` appends -> ":s/a/X/g" replaced both a's on line 2.
    h.case(ctx, target, "nvim#e9 history recall puts the cursor at the end", &.{ ":s/a/X/\r", "j", ":", "\x1b[A", "g", "\r", ":wq", CR }, "aa\naa\n", "Xa\nXX\n");
    // Probe: `:s/a/XY/` Left x3 CR -> "XYb", not "Xb" — Enter runs the WHOLE
    // line, never just the part before the cursor.
    h.case(ctx, target, "nvim#e10 Enter mid-line runs the whole line", &.{ ":s/a/XY/", "\x1b[D\x1b[D\x1b[D", "\r", ":wq", CR }, "ab\n", "XYb\n");

    // Paragraph motions and text objects ({ } ip ap) — nvim-verified.
    const P2 = "aaa\nbbb\n\nccc\nddd\n";
    const P3 = "aaa\n\nbbb\n\nccc\n";
    h.case(ctx, target, "nvim#p1 } lands on the empty line", &.{ "}x", ":wq", CR }, P2, P2);
    h.case(ctx, target, "nvim#p2 d} from col 0 is linewise", &.{ "d}", ":wq", CR }, P2, "\nccc\nddd\n");
    h.case(ctx, target, "nvim#p3 d} mid-line stays charwise", &.{ "lld}", ":wq", CR }, P2, "aa\n\nccc\nddd\n");
    h.case(ctx, target, "nvim#p4 { lands on the empty line", &.{ "G{x", ":wq", CR }, P2, P2);
    h.case(ctx, target, "nvim#p5 d{ deletes back to boundary", &.{ "G$d{", ":wq", CR }, P2, "aaa\nbbb\nd\n");
    h.case(ctx, target, "nvim#p6 dip deletes the paragraph", &.{ "dip", ":wq", CR }, P2, "\nccc\nddd\n");
    h.case(ctx, target, "nvim#p7 dap takes the trailing blank", &.{ "dap", ":wq", CR }, P2, "ccc\nddd\n");
    h.case(ctx, target, "nvim#p8 dip on a blank line", &.{ "jdip", ":wq", CR }, "aaa\n\n\nbbb\n", "aaa\nbbb\n");
    h.case(ctx, target, "nvim#p9 dap on last para takes leading blank", &.{ "Gdap", ":wq", CR }, P2, "aaa\nbbb\n");
    h.case(ctx, target, "nvim#p10 vip d is linewise", &.{ "vipd", ":wq", CR }, P2, "\nccc\nddd\n");
    h.case(ctx, target, "nvim#p11 yap P round-trips", &.{ "yapP", ":wq", CR }, P3, "aaa\n\naaa\n\nbbb\n\nccc\n");
    h.case(ctx, target, "nvim#p12 2} skips a boundary", &.{ "2}x", ":wq", CR }, P3, P3);
    h.case(ctx, target, "nvim#p13 whitespace-only line is no boundary", &.{ "}x", ":wq", CR }, "aaa\n  \nbbb\n\nccc\n", "aaa\n  \nbbb\n\nccc\n");
    h.case(ctx, target, "nvim#p14 cip changes the paragraph", &.{ "cip", "XX", ESC, ":wq", CR }, P2, "XX\n\nccc\nddd\n");
    h.case(ctx, target, "nvim#p15 } at EOF clamps to last line", &.{ "}}x", ":wq", CR }, P2, "aaa\nbbb\n\nccc\ndd\n");
    h.case(ctx, target, "nvim#p16 d2ap takes two paragraphs", &.{ "d2ap", ":wq", CR }, P3, "ccc\n");

    // The cursor never sits past the last character in normal mode, so
    // commands after `$` act on the last character (regression: `$x` used to
    // do nothing and `$dh`/`$d0`/`$db` were all off by one). nvim-verified.
    h.case(ctx, target, "nvim#c1 $x deletes the last character", &.{ "$x", ":wq", CR }, "abc\n", "ab\n");
    h.case(ctx, target, "nvim#c2 $dh deletes before the last", &.{ "$dh", ":wq", CR }, "abc\n", "ac\n");
    h.case(ctx, target, "nvim#c3 $d0 keeps the last character", &.{ "$d0", ":wq", CR }, "abc\n", "c\n");
    h.case(ctx, target, "nvim#c4 $db from end of line", &.{ "$db", ":wq", CR }, "abc def\n", "abc f\n");
    h.case(ctx, target, "nvim#c5 $dF exclusive backward find", &.{ "$dFc", ":wq", CR }, "abc def\n", "abf\n");

    // Regex `/` search: the pattern jumps, then x edits at the match.
    h.case(ctx, target, "regex / search jumps to match", &.{ "/b.d\r", "x", ":wq", CR }, "xxx\nbad\n", "xxx\nad\n");
    // Capture groups in the replacement swap two words.
    h.case(ctx, target, "capture groups in :s replacement", &.{ ":%s/(\\w+) (\\w+)/\\2 \\1/\r", ":wq", CR }, "one two\n", "two one\n");
}
